[build]
  publish = "_book"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    Basic-Auth = "alberto:PMNOX9IF mediolanum:efa2025"
