[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''


    # The Basic-Auth header may not be available on all plans.
    Basic-Auth = "alberto:PMNOX9IF carmen:efa2025 emsimonv@gmail.com:efa2025 cmgromero@yahoo.es:efa2025 rrodriguezmon@gmail.com:efa2025 Cleal.experience@gmail.com:efa2025 lafiyani2112@hotmail.com:efa2025 j.serrano.arconada@gmail.com:142890281" 
