[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

    Basic-Auth = "alberto:PMNOX9IF"

[build]
publish = "_book"
command = "quarto render"

[build.environment]
QUARTO_VERSION = "1.4.553"
