[build]
  publish = "_book"
  command = """
  curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
  dpkg -x quarto-linux-amd64.deb quarto-bin
  export PATH=$(pwd)/quarto-bin/usr/local/bin:$PATH
  quarto render
  """

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
    Basic-Auth = "alberto:PMNOX9IF"