---
title: "游닄 Referencias y bibliograf칤a"
format: html
bibliography: references.bib
csl: apa-es-definitivo-final.csl
lang: es
---

Este documento incluye ejemplos de citas bibliogr치ficas que se presentan a lo largo del contenido.

A lo largo del libro se ir치n incorporando referencias a documentos, estudios y fuentes institucionales que complementan o fundamentan los conceptos tratados en cada m칩dulo.  
Este apartado re칰ne algunas de las principales fuentes utilizadas hasta el momento, y sirve tambi칠n como modelo de citaci칩n. No se trata de una bibliograf칤a t칠cnica exhaustiva, sino de un punto de consulta 칰til para profundizar o contrastar lo aprendido.

* EFPA Espa침a establece los requisitos oficiales para la obtenci칩n de la certificaci칩n EFA Nivel II [@efpa2025].

* La fiscalidad de las Letras, Bonos y Obligaciones del Estado est치 claramente definida por el Tesoro P칰blico [@tesoro_fiscalidad_2025].

* Bernstein desarrolla un enfoque racional de diversificaci칩n a largo plazo [@bernstein2012].

* Fama y French analizan la relaci칩n entre rentabilidad esperada y caracter칤sticas de las acciones [@fama1992].

## 游닀 Bibliograf칤a

::: {#refs}
:::
