{
  "hash": "5803fc61e386d9269482cb1d26165b48",
  "result": {
    "markdown": "---\ntitle: \"Clase 1: Rentas Financieras, Renta Fija, Valoración de activos de renta fija... ![](images/EFA_logo.jpg)\"\nformat:\n  html:\n   toc: true\n   number-sections: true\n   lang: es\n---\n\n\n## Rentas financieras\n\n### Concepto\n\nSe aplica la **herramienta** del interés compuesto a la **valoración de conjuntos de capitales financieros**; más concretamente, por la **amplia utilización** que el mercado hace de ellas, se estudian las rentas financieras, al considerar que gran parte de las **operaciones financieras están utilizando pagos o cobros periódicos en el tiempo**, haciendo **especial hincapié** en los aspectos que afectan a su clasificación y a la valoración de **rentas constantes**.\n\n### Objetivos\n\n-   **Situar el flujo** de cobros o pagos de una renta financiera **en un diagrama temporal** y clasificarlo\n\n-   **Calcular el valor actual y final** de rentas constantes y variables\n\n### Teoría\n\nLas **rentas financieras son conjuntos de capitales financieros que involucran pagos o cobros periódicos en el tiempo**. Estas rentas son ampliamente utilizadas en el mercado financiero y se basan en pagos o cobros periódicos, lo cual justifica su estudio y análisis.\n\nLa renta financiera está compuesta por dos **elementos principales**:\n\n-   **Términos** de la renta: Estos son los distintos capitales financieros o pagos que componen la renta. Cada término representa una **cantidad específica de dinero que se paga o se recibe** en un determinado período de tiempo. Los términos pueden ser iguales o diferentes entre sí, dependiendo de la naturaleza de la renta. Por ejemplo, en una renta fija, los términos suelen ser iguales, mientras que en una renta variable pueden variar en cantidad.\n\n-   **Periodo** de la renta: Es el plazo constante que separa dos términos consecutivos en la secuencia de pagos o cobros de la renta. Este período puede ser **mensual, trimestral, anual** u otra unidad de tiempo, dependiendo de cómo se haya establecido la frecuencia de los pagos o cobros de la renta. Es importante que el período sea constante para poder calcular de manera precisa el valor y la valoración de la renta.\n\nLas rentas **pueden ser clasificadas** de acuerdo a diferentes criterios. Los principales son:\n\n1.  Según la **cuantía de los términos** de la renta:\n\n-   Renta **constante**: cuando las cuantías de todos los términos son iguales.\n-   Renta **variable**: cuando las cuantías de los términos no son iguales.\n\n2.  Según el **número de términos** de la renta:\n\n-   Renta **temporal**: cuando el número de términos es finito.\n-   Renta **perpetua**: cuando el número de términos es infinito.\n\n3.  Según el **periodo de la renta**:\n\n-   Renta **mensual, trimestral, anual,** etc.\n\n4.  Según el **inicio del primer periodo** de la renta:\n\n-   Renta **inmediata**: cuando el inicio del primer periodo de la renta coincide con el instante inicial de valoración.\n-   Renta **diferida**: cuando el inicio del primer periodo de la renta es posterior al instante inicial de valoración.\n\n5.  Según el **instante en que se hace efectiva la cuantía dentro de cada periodo**:\n\n-   Renta **postpagable** o vencida: cuando la cuantía se hace efectiva al final de cada periodo.\n-   Renta **prepagable** o anticipada: cuando la cuantía se hace efectiva al inicio de cada periodo.\n\nAl **clasificar** una renta nos interesará sobre todo identificar entre **dos categorías** principales:\n\n1.  **Renta constante**: En este tipo de renta, los pagos o cobros (términos) tienen un **monto constante en cada periodo**. La renta más típica sería un préstamo hipotecario concedido por el método de amortización francés (cuota constante).\n\n2.  **Renta variable**: En este caso, **los pagos o cobros varían en cada periodo**. Un ejemplo típico es el método de Gordon-Shapiro se utiliza para estimar el valor intrínseco de una acción en función de los dividendos esperados y las tasas de crecimiento.\n\nPara comprender mejor una renta financiera, es útil representar el flujo de cobros o pagos en un diagrama temporal. Este diagrama muestra el eje horizontal como el tiempo y el eje vertical como el monto de los cobros o pagos.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023-CLASES-MARTA_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nPor ejemplo, una renta mensual de 500 euros durante un período de tiempo específico. En el diagrama temporal, los pagos se representan mediante líneas horizontales paralelas.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2023-CLASES-MARTA_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nPor ejemplo, una renta que comienza con un pago de 1.000 euros y experimenta cambios en cada periodo, ya sea en aumento o disminución. En el diagrama temporal, los pagos se representan mediante líneas que varían en cada periodo.\n\n### Cálculos\n\nAdemás de clasificar las rentas financieras, es **fundamental calcular su valor** actual y final **en el contexto del interés compuesto.**\n\n-   El **valor actual** de una renta constante representa la **suma de los pagos descontados en el momento presente**, considerando una tasa de interés adecuada.\n\n-   El **valor final** de una renta constante se refiere al **monto acumulado al final de la serie de pagos**. Estos cálculos se realizan utilizando fórmulas específicas que tienen en cuenta la tasa de interés, el monto de los pagos y el número de periodos.\n\nPara calcular el valor de una renta y aplicar el concepto de **interés compuesto, es habitual trabajar con tipos nominales y efectivos expresados en diferentes frecuencias (mensual, trimestral, anual)**. Es fundamental en este sentido **utilizar el tipo de interés correspondiente a la frecuencia de los cobros y pagos asociados a la renta**, a fin de obtener una valoración precisa y realista. Es decir, que debemos de reflejar adecuadamente la renta en función del periodo en el que se producen los flujos de caja (términos mensuales, por ejemplo) y el período del tipo de interés a aplicar (tendrá que ser mensual en este caso), asegurando así una evaluación precisa y acorde a la situación.\n\nEl valor actual representa la suma de los pagos descontados al presente, teniendo en cuenta una tasa de interés adecuada.\n\n::: {.callout-note appearance=\"simple\"}\nLa fórmula general para calcular el **valor actual de una renta constante** es:\n\n$$V_0=c\\cdot\\frac{1-\\left(1+i\\right)^{-n}}{i}$$\n\nDonde,\n\n-   $V_0$, es el valor actual.\n\n-   $C$, es cuota o cuantía.\n\n-   $i$, es el tipo de interés.\n\n-   $n$, es el tiempo transcurrido.\n:::\n\nPor otro lado, el valor final de una renta constante se refiere al monto acumulado al final de la serie de pagos.\n\n::: {.callout-note appearance=\"simple\"}\nLa fórmula para calcular el **valor final de una renta constante** es: $$V_f=c\\cdot\\frac{\\left(1+i\\right)^{n}-1}{i}$$\n\nDonde,\n\n-   $V_f$, es el valor final.\n\n-   $C$, es cuota o cuantía.\n\n-   $i$, es el tipo de interés.\n\n-   $n$, es el tiempo transcurrido.\n\nEstas fórmulas son fundamentales para calcular el valor actual y final de una renta constante, lo cual permite evaluar la rentabilidad y viabilidad de operaciones financieras que involucran flujos de pagos o cobros periódicos en el tiempo.\n:::\n\nLas fórmulas presentadas anteriormente son para calcular rentas postpagables, es decir, en las que los pagos se realizan al final de cada período. Sin embargo, es posible **convertir una renta prepagable**, en la que los pagos se realizan al inicio de cada período, **en una renta postpagable cambiando el momento de los pagos**.\n\n::: {.callout-note appearance=\"simple\"}\nPara una renta constante prepagable, el valor actual se calcula utilizando la fórmula:\n\n$$V_0=c\\cdot\\frac{1-\\left(1+i\\right)^{-n}}{i}\\cdot(1+i)^n$$\n\nY, el valor final:\n\n$$V_f=c\\cdot\\frac{\\left(1+i\\right)^{n}-1}{i}\\cdot(1+i)^n$$\n:::\n\n::: {.callout-warning appearance=\"simple\"}\n**La diferencia entre ambas fórmulas (perpagables y postpagables) radica en la presencia del factor** $(1 + i)^n$ en la fórmula de la renta prepagable. Este factor tiene en cuenta los pagos anticipados realizados al inicio de cada período, lo cual afecta el valor actual de la renta.\n:::\n\nEs importante entender la diferencia entre estos dos tipos de rentas para poder aplicar las fórmulas correctamente.\n\nPor ejemplo, una **renta postpagable se aplica a un préstamo** en el cual se efectúan pagos periódicos después de cada período. En contraste, una **renta prepagable se relaciona con un contrato de alquiler** en el que se realizan pagos anticipados para asegurar el derecho de disfrute de la propiedad en períodos futuros.\n\n## Renta Fija\n\n### Concepto\n\nUn activo de renta fija es un valor que **representa una deuda para el emisor** y que tiene una retribución que se fija, generalmente, por adelantado.\n\nUn activo de renta fija es, por lo tanto, un valor que representa el derecho a recibir pagos periódicos o al final de la operación, prefijados y regulares en el futuro.\n\nEl emisor de un bono debe seleccionar **las condiciones** (fecha de emisión, fecha de vencimiento, tipo de interés, periodicidad de pago, etc.) que **una vez fijadas no se pueden modificar. Por ese motivo este tipo de activos reciben el nombre de renta fija.**\n\n### Características generales de la renta fija\n\nLos elementos característicos de un título de renta fija son los siguientes:\n\n1.  **Tipo de emisor**: es aquel que obtiene la financiación del mercado y asume la obligación de pagar los cupones y devolver el principal. Puede ser público (administraciones públicas) o privado (bancos y empresas).\n\n2.  **Valor Nominal** (VN): Monto de la deuda contraída por el emisor con el suscriptor, comprador o tenedor del título.\n\n3.  **Precio de emisión** (Pe): Precio al que se emite y suscribe el título en el mercado primario.\n\n4.  **Número de títulos emitidos** (N): Unidades en las que se divide el empréstito.\n\n5.  **Importe de la emisión** (VN x N): Valor total de la emisión calculado multiplicando el valor nominal por el número de títulos emitidos.\n\n6.  **Fecha de emisión**: Fecha en la que se emite y pone en circulación el título de renta fija.\n\n7.  **Fecha de vencimiento**: Fecha en la que finaliza la vida del título y se debe devolver el valor nominal.\n\n8.  **Cupón**: Pago periódico de interés que se calcula como un porcentaje del valor nominal del título.\n\n9.  **Frecuencia de pago**: Periodo en el que se realiza el pago del cupón, que puede ser anual, semestral, al vencimiento, entre otros.\n\n10. **Amortización**: Monto devuelto por el emisor al vencimiento o en fechas preestablecidas, generalmente como un porcentaje del valor nominal.\n\n11. **Rating**: Calificación crediticia asignada al emisor o a la emisión de renta fija, que indica su calidad crediticia y nivel de riesgo.\n\n12. **Vencimiento**: fecha en que se termina de repagar la totalidad de la deuda. En este momento el bono cesa.\n\n13. **Bono cupón cero**: son aquellos instrumentos, emitidos al descuento, que no generan flujos intermedios (no pagan cupones). El rendimiento es el obtenido por la diferencia entre el precio de compra y el de venta o amortización del título.\n\n14. **TIR**: rendimiento del instrumento a priori, que **dependerá de las condiciones de mercado**. No confundir con el cupón con la TIR, ya que el primero es fijo y la segunda dependerá del precio al que se adquiera el título.\n\n15. **TRE**: Tasa de Rentabilidad Efectiva o **rendimiento real obtenido después de realizar la inversión**. Se calcula teniendo en cuenta los flujos de efectivo reales que se generan durante la vida de la inversión, incluyendo los ingresos y los desembolsos de efectivo. La rentabilidad efectiva refleja el rendimiento real de la inversión, **teniendo en cuenta cualquier variación en los flujos de efectivo y las tasas de interés**.\n\nEstos elementos son importantes para comprender y evaluar los títulos de renta fija en términos de su emisor, valor, precio, pagos de intereses, fechas y riesgo crediticio.\n\n**Según el vencimiento del activo**, los títulos de renta fija se pueden clasificar en dos categorías:\n\n1.  **Activos monetarios**: Son aquellos activos de renta fija cuyo **vencimiento** en el momento de la emisión se sitúa generalmente **en torno a los dieciocho meses o en plazos inferiores**. Estos activos suelen tener un plazo de vencimiento corto y se utilizan para cubrir necesidades de financiamiento a corto plazo. Ejemplos de activos monetarios son las Letras del Tesoro y los Pagarés de empresa.\n\n2.  **Activos del mercado de capitales**: Son activos de renta fija cuyo **vencimiento** en el momento de la emisión es **superior a los dieciocho meses**. Estos activos se emiten en plazos más largos y suelen formar parte del mercado de capitales. Los plazos típicos para estos activos son 3, 5, 10, 15, 20 y 30 años. Ejemplos de activos del mercado de capitales son los Bonos y Obligaciones del Estado.\n\nLa clasificación **según el tipo de interés** sería:\n\nActivos con interés **implícito**:\n\n-   Activos **al descuento**: Son activos en los que el interés o rendimiento se obtiene a partir del diferencial entre el precio de suscripción o compra y el precio de venta o amortización. En estos activos, la amortización se realiza al valor nominal. Los ejemplos típicos son las Letras del Tesoro, los Pagarés de Empresa y los Bonos Cupón Cero (STRIPS).\n\nActivos con interés **implícito y explícito**:\n\n-   Los intereses explícitos que devenga un activo de renta fija se denominan cupones.\n\n-   Activos **con prima de emisión**: Son activos en los que el interés total se compone tanto del diferencial de amortización o venta menos la suscripción o compra, como del pago de cupones periódicos. Estos activos **se emiten a un precio inferior al valor nominal** (**bajo par**).\n\n-   Activos **con prima de reembolso**: Son activos de interés explícito en los que el valor de reembolso es superior al valor nominal. Además de los cupones periódicos, al vencimiento **el inversor recibirá un monto superior al valor nominal (amortización sobre par)**.\n\n### Estructura del mercado de deuda pública\n\n#### Activos que se negocian\n\n**Letras del Tesoro**\n\n-   Títulos a corto plazo.\n\n-   Emitidos al descuento.\n\n-   Representados por anotaciones en cuenta en la Central de Anotaciones de BdE.\n\n-   La rentabilidad es la diferencia entre el valor nominal y el precio de adquisición pagado por el inversor.\n\n-   Procedimiento de emisión mediante subasta española.\n\n**Bonos y obligaciones del estado**\n\n-   Títulos a largo plazo. Bonos a 3 y 5 años y Obligaciones a 10, 15 y 30 años.\n\n-   Representados por anotaciones en cuenta en la Central de Anotaciones de BdE.\n\n-   Pagan cupones anuales siendo reembolsables a vencimiento por su valor nominal.\n\n-   Procedimiento de emisión mediante subasta española.\n\n#### Miembros del mercado\n\n**El Tesoro**\n\n-   Cubrir las necesidades de endeudamiento del Estado al menor coste posible.\n\n-   Mantener un adecuado grado de liquidez en el mercado.\n\n-   Ofrecer a los inversores instrumentos financieros atractivos.\n\n**Banco de España**\n\n-   Agente financiero de la deuda pública.\n\n-   Gestiona la Central de Anotaciones.\n\n-   Supervisa el funcionamiento y la transparencia del mercado de Deuda Pública.\n\n**Entidades Gestoras**\n\n-   Llevan las cuentas de quienes no están autorizados a operar directamente a través de la central de Anotaciones.\n\n-   Salvo que sean agencias de valores, pueden ser Titular de Cuenta.\n\n-   Realizan funciones registrales, de compensación y liquidación y de custodia en relación al mercado de deuda pública.\n\n**Creadores de mercado**\n\n-   Entidades financieras cuyo objetivo es favorecer la liquidez del mercado secundario.\n\n-   Cotizan sistemáticamente precios de compra y de venta y operan con unos volúmenes mínimos.\n\n#### Mercado primario: procedimiento de emisión de los valores del Tesoro\n\nEl Tesoro español puede emitir Letras del Tesoro, Bonos y Obligaciones del Estado mediante dos métodos: sindicación u oferta pública.\n\n#### Mercado secundario\n\nLa negociación en el mercado secundario se puede realizar a través de varios sistemas\n\n### Mercado de renta fija privada\n\nEn el mercado de renta fija privada se utilizan diferentes instrumentos, como:\n\n-   Pagarés de empresa\n-   Bonos convertibles\n-   Acciones preferentes\n-   Fondos de titulización de activos\n\n### Rating\n\nEl **rating o solvencia crediticia** conocido también como el **riesgo de crédito (o de contraparte)**, se mide como la posibilidad de que el emisor de un bono no pueda hacer frente a los pagos de los cupones o del principal\n\nPo lo tanto a través del rating podremos **valorar el nivel de solvencia de un emisor y sus perspectivas futuras de pago**. El rating proporciona un indicador de **referencia del riesgo crediticio** que soporta el inversor. Esta calificación se realiza por empresas independientes especializadas en el análisis de riesgos, siendo las principales Moody ́s, Standard and Poor ́s y Fitch.\n\nPor lo general, **cuanto mejor sea la calificación crediticia (rating) de un emisor o de una emisión, menor será la prima de riesgo del bono y, por lo tanto, menor será su rentabilidad exigida**.\n\n### Otros riesgos asociados a la renta fija\n\nLa **denominación de \"renta fija\" puede ser engañosa**, ya que puede dar la impresión de que la rentabilidad está preestablecida y garantizada. Sin embargo, en realidad, lo que es fijo en una inversión de renta fija es el conocimiento previo de los montos, las fechas en que el emisor pagará los cupones y la devolución del principal. Sin embargo, debido a **la variación de los tipos de interés en el mercado, el precio de un título de renta fija puede fluctuar al igual que cualquier otro activo financiero, subiendo o bajando**.\n\nLos riesgos potenciales asociados a la renta fija son:\n\n• **Riesgo de precio**\n\n• **Riesgo de reinversión**\n\n• Riesgo de crédito\n\n• Riesgo de inflación\n\n• Riesgo de tipo de cambio\n\n• Riesgo de amortización anticipada\n\n• Riesgo de liquidez\n\nEn esta parte **nos centraremos en los dos primeros, entendidos como el riesgo de tipo de interés**:\n\n-   El **riesgo de precio es la principal fuente de incertidumbre** a la que se enfrenta un inversor en productos de renta fija. Todos los productos de renta fija están sujetos a este riesgo.Ya que **cuando el tipo de interés de mercado sube, el precio del bono baja.Y, viceversa**, cuando el tipo de interés de mercado baja, el precio del bono sube.\n\n-   El **riesgo de reinversión** aparece en aquellos activos de renta fija con rendimiento explícito y se refiere al hecho de que durante el transcurso de la vida de un bono, se asume la **incertidumbre sobre la reinversión del importe cobrado del cupón**. El cupón se reinvertirá en otro producto de renta fija que tendrá, muy probablemente, un tipo de interés superior o inferior al del producto en su momento inicial.\n\n### Relación precio-TIR: principios de Malkiel\n\nLa relación precio-TIR sigue los principios de Malkiel, que incluyen:\n\n-   El valor de un activo de renta fija varía en sentido inverso a su rentabilidad.\n-   Los activos con menor cupón experimentan mayores cambios de valor.\n-   Un incremento de la TIR supone una caída de precio inferior a la caída provocada por una disminución de la TIR.\n\n### Curva y estructura temporal de los tipos de interés (ETTI)\n\n#### Concepto\n\nLa curva de tipos de interés es una herramienta importante en el mercado financiero que proporciona información sobre las rentabilidades de los activos de renta fija en relación con sus vencimientos. La curva se representa gráficamente trazando los rendimientos de los bonos con diferentes vencimientos. La estructura temporal de los tipos de interés, por su parte, muestra los rendimientos de los bonos cupón cero y se utiliza para analizar la relación entre los tipos de interés y los vencimientos.\n\nEl perfil de la curva de tipos de interés, o de un tramo de ella, puede ser plano, creciente o decreciente. Un perfil plano indica que los rendimientos son similares para todos los vencimientos, mientras que un perfil creciente indica que los rendimientos aumentan a medida que aumenta el vencimiento. Por el contrario, un perfil decreciente indica que los rendimientos disminuyen a medida que aumenta el vencimiento.\n\nEs importante tener en cuenta que si hay cambios en las expectativas o variables relevantes, las curvas de tipos de interés se desplazan y modifican su perfil. Por ejemplo, si se espera que la inflación aumente, esto puede provocar un aumento en los tipos de interés a largo plazo y una pendiente más pronunciada en la curva. En general, la curva de tipos de interés es una herramienta valiosa para los inversores y analistas financieros que buscan entender las tendencias del mercado y tomar decisiones informadas sobre sus inversiones.\n\n#### Teorías explicativas de la ETTI\n\nLa curva de tipos de interés muestra las rentabilidades de los activos de renta fija en relación con sus vencimientos. Existen diferentes teorías que explican cómo se forma la curva. La Teoría de la Preferencia por la Liquidez establece que la curva debe ser creciente, ya que los inversores prefieren invertir a corto plazo para poder convertir en liquidez los activos si es necesario. La Teoría de las Expectativas del Mercado indica que la curva se forma en función de las expectativas de los inversores sobre cómo evolucionarán los tipos de interés en el futuro. Finalmente, la Teoría del Hábitat Preferido sintetiza estas teorías y establece que la oferta y la demanda de activos financieros debe ajustar sus plazos según el \"hábitat\" en el que se encuentren, existiendo primas para aquellos vencimientos donde hay una demanda insuficiente. En general, estas teorías son útiles para entender las tendencias del mercado y tomar decisiones informadas sobre las inversiones.\n\nUn desarrollo más amplio de las teorías explicativas de la estructura temporal de los tipos de interés (ETTI) sería:\n\n-   De la Teoría de la Preferencia por la liquidez, se infiere que la curva de rendimientos de una inversión será siempre creciente en función del tiempo, ya que en principio un inversor preferirá invertir a corto plazo que a largo plazo, al poder conseguir convertir antes en liquidez los activos si así le fuera necesario.\n\n-   La Teoría de las Expectativas del Mercado, enuncia que la ETTI se forma de manera exclusiva en función de las expectativas que tienen los potenciales inversores en relación a cómo van a evolucionar los tipos de interés en el futuro. Por tanto, la curva sería creciente cuando se espere que los tipos vayan a subir debido a que haya por ejemplo una elevada inflación, y sería descendente cuando la expectativa fuera de bajada de la inflación.\n\n-   La Teoría del Hábitat Preferido, por su parte ha tratado de sintetizar estas teorías, estableciendo que el equilibrio de mercado obliga a que la oferta y la demanda de activos financieros debe ajustar sus plazos en cada momento, según el \"hábitat\" en el que nos encontremos, existiendo primas para aquellos vencimientos donde hay una demanda insuficiente, de tal manera que dichas primas serían las que inducirían a los inversores al abandono de sus hábitats preferidos, pasando de largo a corto plazo o viceversa.\n\n#### Ejemplo ETTI\n\nSi las cotizaciones actuales de los bonos cupón cero a 3,5 y 10 años es del 100% y sus valores de reembolso son: 115,76%, 127,63% y 162,89% respectivamente, ¿cuál será el perfil que adopte la ETTI?\n\n<!-- -->\n\na.  Positiva.\n\nb.  Negativa.\n\nc.  Plana.\n\nd.  Exponencial.\n\n::: {.FOO .callout-tip appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nPara saber que el perfil adoptará la ETTI simplemente deberemos calcular el valor que toma la TIR de los 3 bonos cupón cero referidos y, ordenalos en función de su plazo de vencimiento. De forma que si el precio de un bono cupón cero viene dado por:\n\n$$P_0(\\%)=\\frac{Reembolso(\\%)}{(1+TIR)^{n}}$$\n\n**BONO 1**\n\n$$100=\\frac{115,76}{(1+TIR)^{3}}=>TIR=5\\%$$\n\n**BONO 2**\n\n$$100=\\frac{127,63}{(1+TIR)^{5}}=>TIR=5\\%$$\n\n**BONO 3**\n\n$$100=\\frac{162,89}{(1+TIR)^{10}}=>TIR=5\\%$$\n\nluego, el perfil que adoptará la ETTI será plano ya que para los tres bonos la tasa interna de rentabilidad **(TIR) a, 5 y 10 años es igual al 5%**.\n:::\n\n### Medición y gestión del riesgo de tipo de interés\n\n#### Sensibilidad\n\nLa sensibilidad es una **herramienta** valiosa para determinar cómo se comportará el precio de un bono ante pequeñas variaciones en la TIR. Es por tanto, una medida de riesgo en la gestión de activos de renta fija. Esta medida **nos indica cuán \"sensible\" es el precio del bono (en términos absolutos, viene dada en unidades monetarias) a las fluctuaciones absolutas que se producen en los tipos de interés**.\n\n-   En **escenarios de tipos de interés bajos**, un bono con una **sensibilidad mayor experimentará un aumento de precio más significativo** si se produce una variación en la TIR.\n\n-   Por otro lado, en **escenarios de tipos de interés altos**, un bono con una **sensibilidad menor experimentará una disminución de precio menor** si hay una variación en la TIR.\n\nSin embargo, como la sensibilidad refleja las variaciones de los precios en términos absolutos, **no es adecuada para comparar bonos con diferentes precios y características**. En este caso, se requiere un análisis de la duración de los bonos.\n\nPara hallar la sensibilidad (o sensibilidad absoluta) ante cambios en el precio, calcularemos lo siguiente:\n\n::: {.callout-note appearance=\"simple\"}\n1.  La Duración de Macaulay\n\n$$D=\\frac{\\sum_{t=1}^{n}\\frac{F_t\\cdot t}{\\left(1+r\\right)^t}}{P}$$\n\n2.  La Duración corregida\n\n$$D_{corregida}=\\frac{D}{\\left(1+TIR\\right)} $$\n\n3.  La propia sensibilidad\n\n$$S= Duracion\\,corregida \\cdot \\frac{Precio\\,entero}{100}$$\n\nPodemos usar la sensibilidad como una aproximación lineal del nuevo valor de un bono ($P_1$) ante una variación absoluta de la TIR ($\\Delta TIR$) es:\n\n$$P_1\\simeq P_0 + ((-S)\\cdot\\Delta TIR)$$\n:::\n\n#### Duración\n\nLa **duración de Macaulay** es una de las características más importantes que definen un bono. Los gestores de renta fija suelen utilizar esta medida debido a sus propiedades, ya que **permite establecer relaciones fundamentales entre** la estructura de un bono, **su TIR y su precio**.\n\nLa duración es la media de los periodos de pago de los flujos de un bono ponderados por el peso que representa el valor actual de los mismos en el precio del bono.\n\n::: {.callout-note appearance=\"simple\"}\nDuración de Macaulay (o simplemente Duración)\n\n$$D=\\frac{\\sum_{t=1}^{n}\\frac{F_t\\cdot t}{\\left(1+r\\right)^t}}{P_0}$$\n\nDonde,\n\n-   $D$, Duración de Macaulay expresada en años.\n\n-   $F_t$, Flujos a percibir por la tenencia de un bono (cupón y principal).\n\n-   $P_0$, es el precio entero de un bono o valor actual del mismo ($V_0$).\n\n-   $r$, es la TIR.\n\n-   $t$, es el tiempo hasta el vencimiento de cada uno de los flujos del bono.\n:::\n\nEs por lo tanto, una media ponderada de la vida de un bono, es decir, la \"vida media\" del bono. La duración **se expresa** en unidades temporales, **normalmente en años**.\n\n#### Propiedades de la Duración\n\nDe la expresión general para el cálculo de la duración, se puede deducir que **un bono cupón cero (un solo flujo en la fecha de vencimiento) tiene una duración igual a su vencimiento**.\n\nLa duración **puede definirse también como una medida de la sensibilidad relativa de un bono**. Es decir, relaciona las variaciones relativas del precio con las variaciones relativas de la TIR.\n\nDe forma que también podemos deducir que:\n\n-   Ante previsiones de **subidas en los tipos de interés**, será **más interesante** para el inversor en renta fija invertir en **bonos con una duración pequeña**.\n\n-   Ante previsiones de **bajadas en los tipos de interés**, será **más interesante** para el inversor en renta fija invertir en **bonos con más duración**.\n\nSi relacionamos la duración con el vencimiento de un bono, manteniendo constante la estructura de los flujos y la TIR, podemos afirmar que en general: a **mayor plazo de amortización, mayor duración**.\n\n::: {.callout-important appearance=\"simple\"}\nCon una **excepción**: y es que para bonos bajo la par con vencimientos largos, el incremento de la duración a medida que aumenta el plazo de amortización, presenta un punto de inflexión a partir del cual se invierte la tendencia inicial.\n:::\n\nDe la relación entre la duración y la TIR, podemos deducir que: **cuando aumenta la TIR, disminuye la duración.**\n\nDe la relación entre la duración y la periodicidad de los cupones podemos extraer la siguiente propiedad: **a mayor frecuencia en el pago de cupones menor duración**. Ya que al aumentar la frecuencia en el pago de cupones disminuye la importancia relativa del último flujo, ya que el aumento de la frecuencia incrementa el valor actual de los cupones. Por lo tanto, este efecto se traduce en una disminución de la duración.\n\nDe la relación entre la duración y el paso del tiempo, y siempre que la TIR permanezca constante, se derivan dos propiedades muy importantes. La primera es:\n\n-   **Con el transcurso del tiempo**, los plazos de los flujos del bono se hacen más pequeños y, por lo tanto, **la duración también disminuye**.\n\n-   A **medida que disminuye la vida pendiente de un bono**, también **disminuye su duración**.\n\n#### Duración corregida o modificada\n\nHemos visto, dos medidas que relacionan las variaciones del precio de un bono con las variaciones de su TIR:\n\n-   La **sensibilidad**, donde la **relación** se da a través **de magnitudes** **absolutas**, con lo que existe el problema de comparar entre diferentes bonos.\n\n-   La **duración**, donde la **relación** se realiza a través **de magnitudes relativas**, con lo que es posible la comparación para diferentes bonos.\n\nEn este caso, la problemática se produce en la interpretación económica de las magnitudes. Recordemos que la duración relaciona la variación relativa del precio con la variación relativa de la TIR, pero esta última, no tiene una fácil interpretación económica. Para relacionar los dos problemas, recurriremos al cálculo de la duración corregida, o duración modificada.\n\nMatemáticamente su expresión es:\n\n::: {.callout-note appearance=\"simple\"}\nDuración corregida expresada en años\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}=\\frac{D}{\\left(1+TIR\\right)} $$\n\n-   Si la queremos expresada en porcentaje\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}\\cdot\\frac{1}{100}$$\n:::\n\nCuando hablamos de **volatilidad de los bonos u obligaciones** nos estamos refiriendo a la sensibilidad de su precio de mercado con relación a los cambios que se produzcan en el tipo de interés de mercado (su rendimiento). Así que l**a podemos definir como la variación que se produce en el precio del bono con respecto a un incremento (o decremento) de cien puntos básicos (1%) de su rendimiento (TIR) hasta el vencimiento**.\n\n::: {.callout-note appearance=\"simple\"}\nDuración corregida para estimar el efecto en precio de variaciones en la TIR\n\n$$\\frac{\\Delta P}{P}\\simeq  \\frac{P_1-P_0}{P_0}\\simeq \\left(-D_{corregida}\\right)\\cdot\\Delta TIR$$\n\nAlternativamente, la Duración corregida para estimar el efecto en precio de variaciones en la TIR la podemos expresar como,\n\n$$P_1\\simeq P_0\\cdot\\left[1+((-D_{corregida})\\cdot\\Delta TIR)\\right]$$\n\nDonde,\n\n-   $P_1$, es el precio estimado del bono ante una variación de la TIR.\n\n-   $P_0$, es el precio actual del bono .\n\n-   $D_{corregida}$, es la duración corregida.\n:::\n\nConcretando, el precio de los bonos está inversamente relacionado a su rendimiento; **la duración modificada actúa como un multiplicador dado que cuanto más grande sea, mayor será el impacto en el precio de los bonos ante un cambio de los tipos de interés**; y, por último, para una duración modificada determinada, cuánto mayores sean las variaciones en el tipo de interés, mayor será el porcentaje de cambio en el precio.\n\n#### Inmunización\n\nEl riesgo de tipo de interés es uno de los mayores riesgos a los que se enfrenta un inversor en renta fija, debido a su impacto en el precio y la reinversión de los cupones. Una subida de los tipos de interés reduce el valor del activo, mientras que una bajada de los tipos de interés implica una reinversión de los cupones a tipos más bajos. **Los activos con rendimiento implícito no están expuestos al riesgo de reinversión.**\n\nEl horizonte temporal de la inversión es el factor clave que determinará si el inversor prefiere que los tipos de interés suban o bajen. **Si el horizonte temporal es corto, el efecto precio domina y el inversor preferirá que los tipos de interés bajen. Si el horizonte temporal es largo, el efecto reinversión es mayor y el inversor preferirá que los tipos de interés suban.**\n\nPara lograr la **inmunización**, es importante que la duración y el horizonte temporal de la inversión estén homogeneizados. La duración de Macaulay es una medida útil para evaluar la sensibilidad de los precios de los bonos a los cambios en las tasas de interés. La inmunización **se logra haciendo coincidir la duración y el horizonte temporal de la inversión**, lo que garantiza una rentabilidad mínima igual a la TIR inicial del bono.\n\nHay **tres posibles situaciones** al realizar una inversión:\n\n-   Si la **duración es igual al horizonte temporal, la cartera está inmunizada**.\n\n-   Si la **duración es mayor que el horizonte temporal**, el inversor deberá vender los activos al final del horizonte temporal y asumir un **riesgo de precio**.\n\n-   Si la **duración es menor que el horizonte temporal**, la inversión no estará inmunizada y el inversor deberá hacer una nueva inversión asumiendo el **riesgo de reinversión**.\n\n#### Resumen de fórmulas\n\n![](images/Captura%20de%20pantalla%202023-07-12%20a%20las%2012.54.38.png)\n\n## Valoración de activos de renta fija a corto y a largo plazo\n\nLa **valoración de un bono** se realiza mediante la **actualización** de los flujos futuros a las tasas de interés exigidas por el mercado.\n\nEl rendimiento o la **rentabilidad** de un activo de renta fija **se expresa anualmente** a través del régimen de **interés simple o** del régimen de interés **compuesto**.\n\nEl régimen de interés **simple se usará** básicamente para el cálculo de las rentabilidades de los activos de renta fija a más corto plazo, es decir, **para vencimientos inferiores o iguales al año natural** (Letras del Tesoro y Pagarés de empresa).\n\nLas **bases de cálculo** establecen la unidad de tiempo a la que se refiere un tipo de interés determinado. Por extensión se suele llamar base a la combinación de base y método de cálculo. Las bases más usuales son: la **actual y 360 días**.\n\nEl régimen de **interés compuesto** se usará fundamentalmente **a través de la TIR** para expresar la rentabilidad de un activo con interés explícito. También se utilizará para el cálculo del rendimiento de activos con interés implícito y vencimientos superiores al año natural.\n\n**El precio de los bonos y de las obligaciones** (activos de renta fija a medio y largo plazo) es igual al valor presente de sus flujos de caja (cash flows) futuros, los cupones y el principal, descontados a un tipo de interés de mercado.\n\n| Método               |     Base     | Régimen de interés | Tipo de interés |\n|:---------------------|:------------:|:------------------:|:---------------:|\n| Mercado monetario    | Hasta 1 año  |     Actual/360     |     Simple      |\n|                      | Más de 1 año |     Actual/360     |    Compuesto    |\n| Mercado de capitales |   Siempre    |   Actual/Actual    |    Compuesto    |\n\nLas **dos formas de expresar el valor de un activo de renta fija**, el valor actual y la TIR, son herramientas importantes en la valoración y análisis de inversiones en este tipo de activos.\n\n-   **Valor Actual** ($P_0$): Se determina aplicando una tasa de descuento o tasa esperada de rendimiento al flujo de efectivo esperado del activo. Este valor actual representa el precio esperado del activo.\n\n-   **Tasa Interna de Rendimiento (TIR)**: Se calcula utilizando el precio de mercado del activo o su valor actual. La TIR es la tasa de retorno esperada del activo, es decir, la tasa que iguala el valor actual del flujo de efectivo del activo con su precio de mercado.\n\nCasos particulares en la valoración de un bono:\n\n1.  Cálculo del precio de un bono con pago de cupones no anuales:\n\n    -   Se calcula el valor presente de cada cupón teniendo en cuenta el plazo y la tasa de descuento adecuada.\n\n    -   Se suma el valor presente de los cupones y el valor presente del valor nominal para obtener el precio del bono.\n\n2.  Cálculo del precio de un bono con pago de cupón anual en una fecha cualquiera:\n\n    -   Se calcula el tiempo hasta la fecha de pago del cupón y se aplica la tasa de descuento correspondiente para obtener el valor presente del cupón. Deberemos tener muy en cuenta la fracción de año que falta para el pago del primer cupón.\n\n    -   Se suma el valor presente de los cupones y el valor presente del valor nominal para obtener el precio del bono.\n\n3.  Cálculo del precio de un bono considerándolo como una renta:\n\n    -   Se calcula el valor presente de los flujos de efectivo generados por los cupones y el valor nominal a lo largo de la vida del bono. Podemos considerar el pago de cupones periódicos como una renta constante, y la amortización del principal, como un bono cupón cero.\n\n    -   Se suma el valor presente de los flujos de efectivo para obtener el precio del bono.\n\n4.  Cálculo del precio de un bono cupón cero:\n\n    -   Se calcula el valor presente del valor nominal utilizando el mismo procedimiento (actualización de los flujos del bono), sólo que se simplifica al calcular el valor actual de un solo flujo.\n\n    -   El precio del bono cupón cero es igual al valor presente del valor nominal.\n\n5.  Precio ex-cupón y cupón corrido:\n\n    -   El **precio ex-cupón** de un bono, es la **diferencia entre el precio entero y el cupón corrido** del bono. **En la mayoría de los mercados** secundarios de renta fija, l**os activos cotizan en precio ex-cupón**.\n\n    -   El **cupón corrido es el interés devengado del próximo cupón**. Se calcula como una ponderación simple del próximo cupón.\n\n    -   **El precio entero es lo que efectivamente vale el bono** y, por lo tanto, el resultado de la actualización de los flujos del bono a la TIR de mercado.\n\n### Resumen\n\nLa **relación** entre el **precio** de un bono, el **cupón y la TIR**\n\n| **Con Prima**              | **Emisión de Bonos**   | **Con Descuento**          |\n|----------------------------|------------------------|----------------------------|\n| Sobre la par               | A la Par               | Bajo La par                |\n| Rentabilidad (-) implícita | Rentabilidad = % Cupón | Rentabilidad (+) implícita |\n| TIR \\< Cupón               | TIR = Cupón            | TIR \\> Cupón               |\n| P \\> VN                    | P = VN                 | P \\< VN                    |\n\n-   Si el **precio del bono es igual a su valor nominal, la TIR será igual al cupón**. Esto significa que el rendimiento del bono será igual al cupón que se paga.\n\n-   Si el **precio del bono es mayor que su valor nominal, la TIR será menor** que el cupón.\n\n-   Si el **precio del bono es menor que su valor nominal, la TIR será mayor** que el cupón.\n\nLa relación entre tipos de interés del mercado y los precios de los bonos\n\n| TIPOS     | PRECIO        | TIR   |\n|-----------|---------------|-------|\n| Si ↑ t/ i | ↓ Precio bono | ↑ TIR |\n| Si ↓ t/ i | ↑ Precio bono | ↓ TIR |\n\n::: {.callout-important appearance=\"simple\"}\nPara hacer la **valoración** de activos de renta fija, en la mayoría de casos, y especialmente cuando tengan cupón corrido, utilizamos la **CALCULADORA FINCIERA CASIO FC 200V**\n\n-   **Precio/TIR/CC** =\\> CASIO FC 200V **(función BOND)**\n\n-   **TRE** =\\> calculamos **sin emplear ninguna función** financiera\n:::\n\nDescripción de los **distintos precios de los bonos cuando hay cupón corrido**:\n\n1.  Precio **Entero**: Es el precio cotizado en el mercado para un bono, incluyendo el valor del cupón corrido.\n\n2.  Precio **Sucio**: También conocido como \"Precio Ex cupón\", es el precio de un bono sin incluir el valor del cupón corrido. Es el precio al que se negocia el bono en el mercado secundario sin tener en cuenta los intereses acumulados.\n\n3.  Precio **Efectivo**: Es el precio limpio del bono, es decir, el precio sin incluir el valor del cupón corrido.\n\n**Analíticamente** y con los **distintos nombres** que podemos encontrar, tenemos:\n\n|                       |                                   |\n|-----------------------|-----------------------------------|\n| **NOMBRE**            | **COMPOSICIÓN**                   |\n| Precio **Entero** =   | Precio cotización + Cupón Corrido |\n| Precio **Sucio** =    | Precio Ex cupón + Cupón Corrido   |\n| Precio **Efectivo** = | Precio Limpio + Cupón Corrido     |\n\n**En la calculadora Casio FC 200V, las variables se definen mediante:**\n\n| **VARIABLE** | **TRADUCCIÓN**                          |\n|--------------|-----------------------------------------|\n| PRC          | Precio ex cupón, limpio o de cotización |\n| INT          | Cupón corrido                           |\n| CTS          | Precio entero, sucio o coste efectivo   |\n\n### Cálculos\n\n::: {.callout-note appearance=\"simple\"}\nTipos de interés spot y forward\n\n-   Para periodos **inferiores al año**, capitalización **simple** (a 6 meses dentro de 6):\n\n$$(1+_{0}S_{12} \\cdot \\frac{12 }{12 })=(1+_{0}S_{6} \\cdot \\frac{6 }{12 })\\cdot(1+f_{6,12}\\cdot \\frac{6 }{12 })$$\n\n-   Para periodos **superiores al año**, capitalización **compuesta** (a 1 año dentro de un año):\n\n$$(1+_{0}S_{2})^{2}=(1+_{0}S_{1})^1\\cdot(1+f_{1,2})^1$$ Donde,\n\n-   $_{0}S_{1}$, es el tipo spot o de contado; el subíndice que aparece a la derecha nos indica el momento en que dicho interés está vigente y, el de la derecha, el número de periodos de vigencia.\n\n-   $f_{1,2}$, es el tipo forward obtenido a partir de los tipos spot; el subíndice nos indica el periodo en que dicho interés estará vigente.\n\n[**Ejercicios para practica los tipos de interés implícitos o forward**](https://monografia-tipos-spot-forward.netlify.app/)\n:::\n\n::: {.callout-note appearance=\"simple\"}\nPrecio de un activo de Renta Fija (interés implícito)\n\n-   **Mercado monetario (Hasta 1 año, capitalización simple)**\n\n$$P_0=\\frac{100}{\\left(1+i\\cdot\\frac{Actual}{360}\\right)}$$\n\n-   **Mercado monetario (Más de 1 año, capitalización compuesta)**\n\n$$P_0=\\frac{100}{(1+i)^{Actual/360}}$$\n\ndonde,\n\n-   $P_0$, es el precio del activo, expresado en porcentaje sobre el nominal.\n\n-   $i$, es el tipo de interés.\n\n-   $Actual$, es el número de días que ha mantenido el inversor el activo en su poder.\n:::\n\n::: {.callout-note appearance=\"simple\"}\nPrecio de un activo de Renta Fija (interés explícito)\n\n$$P_0=\\frac{C_1}{(1+TIR)}+\\frac{C_2}{(1+TIR)^2}+\\ ... \\ +\\frac{C_t}{(1+TIR)^t}$$\n\nDonde,\n\n-   $P_o$, es el precio o valor actual\n\n-   $C_t$, es el cupón en el momento $t$\n\n-   $TIR$, es la tasa de descuento o TIR\n:::\n\nLa Tasa Interna de Rentabilidad (TIR) es una medida de rentabilidad a priori que estima anticipadamente el rendimiento de una inversión. Se calcula considerando los flujos de efectivo futuros y el desembolso inicial de la inversión. La TIR asume que los flujos de efectivo se reinvierten a una tasa constante y se basa en la suposición de una curva de tipos de interés plana.\n\n::: {.callout-note appearance=\"simple\"}\nTasa de rentabilidad efectiva (TRE, o rentabilidad efectiva o a posteriori)\n\n$$P_f=P_0 \\cdot \\left(1+{TRE}\\right)^t$$\n\nDonde,\n\n-   $P_f$, es el precio final o valor final\n\n-   $P_o$, es el precio o valor actual\n\n-   $TRE$, es la rentabilidad efectiva o TRE\n:::\n\nPor otro lado, la Tasa de Rentabilidad Efectiva (TRE) es el **rendimiento real obtenido después de realizar la inversión**. Se calcula teniendo en cuenta los flujos de efectivo reales que se generan durante la vida de la inversión, incluyendo los ingresos y los desembolsos de efectivo. La rentabilidad efectiva refleja el rendimiento real de la inversión, **teniendo en cuenta cualquier variación en los flujos de efectivo y las tasas de interés**.\n\n**Cada una de estas medidas de rentabilidad tiene su utilidad** y se utiliza en diferentes etapas de la evaluación y seguimiento de una inversión de Renta Fija. **La TIR es útil para estimar** el rendimiento potencial de una inversión antes de realizarla, mientras que **la rentabilidad efectiva proporciona una medida más precisa del rendimiento real después de la inversión**.\n\nAmbas medidas son importantes para tomar decisiones informadas sobre inversiones y evaluar su desempeño ya que, **en la medida en que el tipo de interés al que se podrán reinvertir los cupones no coincida con la TIR, su rentabilidad efectiva (TRE) en el vencimiento diferirá de esa TIR**.\n\nEl **cupón corrido** representa el valor proporcional del próximo pago de cupón que se paga al comprador del bono si la fecha de compra es posterior a la fecha de pago del cupón anterior.\n\n::: {.callout-note appearance=\"simple\"}\nCálculo del cupón corrido\n\n$$CC=\\frac{D_c}{D_t}\\cdot C$$\n\nDonde,\n\n-   $CC$, es el cupón corrido.\n\n-   $D_{c}$, es el tiempo, en días, transcurrido desde el pago del último cupón.\n\n-   $D_{t}$, es el tiempo, en días, que transcurre entre el pago de dos cupones consecutivos (días totales de devengo del cupón).\n\n-   $C$, es el importe del cupón que se paga periódicamente.\n:::\n\n### Ejemplos de valoración\n\n1.  Un bono cupón cero adquirido por 88,333%, con vencimiento a 4 años. ¿Indique cuál de las siguientes afirmaciones es correcta?:\n\n<!-- -->\n\na.  Su TIR es del 3,15%\n\nb.  La TRE es del 3,15%\n\nc.  La rentabilidad acumulada al vencimiento es del 11,667%\n\nd.  Todas las respuestas son correctas.\n\n::: {.callout-note appearance=\"simple\"}\nCalculamos la TIR del bono como un descuento en capitalización compuesta:\n\n$$P_0=\\frac{100\\ (reembolso \\ del  \\ 100\\%)}{\\left(1+TIR\\right)^n}$$ de forma que, $$88,333=\\frac{100}{\\left(1+TIR\\right)^4}$$\n\nsi resolvemos por la TIR, tenemos\n\n$$TIR=0.0315(3,15\\%)$$\n\nEn el caso de la TRE, empleamos su fórmula,\n\n$$C_4=C _0\\cdot (1+TRE)^4$$ al sustitur\n\n$$100=88.333\\cdot (1+TRE)^4$$ tenemos que\n\n$$TRE=0.0315(3,15\\%)$$\n\n**La TIR coincidirá con la TRE ya que no hay flujos de caja** que hayan de ser reinvertidos. De forma que el **riesgo**, derivado de la **incertidumbre sobre el tipo de interés**, al que se reinvertirán los cupones, **se elimina** ya que se aplica la TIR desde el inicio de la inversión y hasta el final de la misma:\n\n$$TIR=TRE=0.0315(3,15\\%)$$\n\nFinalmente, calculamos la rentabilidad acumulada del periodo como:\n\n$$r_{\\left(acumulada\\:a\\:vencimiento\\right)}=100\\%-88.333\\%=11.667\\%$$\n:::\n\n2.  El 19 de noviembre de 2016 se compra un bono que vence, exactamente, dentro de tres años. Hemos pagado un 102,35% de su nominal, con una TIR del 4,39% y paga un cupón anual del 5,25%. Si el inversor tiene una política de reinversión de los dividendos y teniendo en cuenta el siguiente esquema de tipos de interés para depósitos a un año, ¿cuál es la tasa de rentabilidad efectiva (TRE) de esta inversión a la fecha de vencimiento?\n\n| Años     | Tipos de interés para depósitos a un año |\n|----------|------------------------------------------|\n| 19-11-17 | 3,00%                                    |\n| 19-11-18 | 2,25%                                    |\n| 19-11-19 | 1,25%                                    |\n\na\\. 4,30%\n\nb\\. 4,42%\n\nc\\. 4,25%\n\nd\\. Ninguna de las anteriores.\n\n::: {.callout-note appearance=\"simple\"}\nRecordemos que la Tasa de Rentabilidad Efectiva (TRE) se define como aquella rentabilidad media anual que tiene en cuenta las tasas de reinversión de los ingresos de una operación, medida mediante capitalización compuesta. Y su expresión es la siguiente:\n\n$$V_f=V_0\\left(1+i_{TRE}\\right)^n$$\n\nDe forma que necesitaremos el valor final de la inversión (que lo calculamos), el valor inicial o precio (es un dato en este caso). De manera, que para hallar cual será el valor al final de la inversión teniendo en cuenta la reinversión a los tipos que nos dan, calculamos primero todos los flujos, esto es, de las cuatro inversiones realizadas:\n\n$$V_f=5.25\\left(1+0.03\\right)\\left(1+0.0225\\right)+5.25\\left(1+0.0225\\right)+105.25$$ $$V_f=116.14729$$\n\nUna vez que ya conocemos el valor final $V_f$ y el valor inicial $V_0$, planteamos la fórmula de la TRE y resolvemos por el tipo de interés $i_{TRE}$:\n\n$$V_f=V_0\\left(1+i_{TRE}\\right)^n$$\n\nDonde,\n\n$$i_{TRE}=\\left(\\frac{V_f }{V_0}\\right)^{\\frac{1 }{n }}-1$$\n\nQue al sustituir y calcular, obtenemos un resultado de:\n\n$$i_{TRE}=\\left(\\frac{116.14729}{102.35}\\right)^{\\frac{1}{3}}-1=0.04305(4.3\\%)$$\n:::\n\n3.  Si 1 de marzo de 2025 se compró un bono con cupón del 4,25% emitido el 1 de marzo de 2024 que vence el 28 de febrero de 2028. Si en activos similares el mercado se mueve en rentabilidades del 3,50% el precio en porcentaje sobre el nominal es aproximadamente:\n\n\n```{=html}\n<!-- -->\n```\n\na.  100%\n\nb.  100,75%\n\nc.  102,11%\n\nd.  102.75%\n\n::: {.callout-note appearance=\"simple\"}\nEn este caso nos piden calcular el precio, pero NO indica de qué precio se trata, si es el precio entero (o sucio), o por el contrario el precio excupón (o de cotización); luego eso puede generar dudas. No obstante, si nos fijamos en este caso concreto a pesar de darnos fechas concretas (y NO términos) ambos precios coinciden (PS=PL), ya que **no existe cupón corrido** debido a que la adquisición del título se lleva a cabo justo en el momento del pago del 1 er cupón (1).\n\nPor otra parte, hay que recordar que **se coge la fecha de compra para el cálculo**, y NO la fecha de emisión ...ya que no se adquiere en la emisión como ya se ha comentado, sino que es adquirido justo al finalizar el primer año (comienzo del segundo año). Luego si lo resolvemos con la **calculadora financiera Casio FC200V** tenemos que:\n\n-   Función: \"BOND\"\n\n-   SET: \"Annu/Date\"\n\n-   d1 = 01032025+ EXE\n\n-   d2 = 28022028 + EXE\n\n-   RDV = 100 + EXE\n\n-   CPN = 4,25 + EXE\n\n-   PRC = 0 + EXE\n\n-   YLD = 3,5% + EXE\n\nAhora, con el cursor, volvemos sobre \"PRC\" y pulsamos \"SOLVE\".\n\nResultado:\n\n-   PRC = - 102,11% (precio: excupón, o de cotización)\n\n-   INT = - 0,00 (cupón corrido)\n\n-   CTS = - 102,11% (**precio entero o sucio**)\n:::\n\n4.  Sea una emisión de pagarés a 18 meses con precio de emisión de 43.937 euros y 50.000 euros de valor nominal. Si seis meses después los pagares cotizan a 45.000 euros, ¿cuál es el tipo de interés al que están cotizando los pagarés en este momento?\n\n<!-- -->\n\na.  9%.\n\nb.  Menor del 9%.\n\nc.  Superior al 9%.\n\nd.  No puede saberse con estos datos.\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nCon los datos del enunciado,\n\n-   $P_0=45000$\n\n-   $Nominal= 50000$\n\n-   $n=12 \\ meses$\n\ny la fórmula del precio de un pagaré/letra,\n\n$$P_o=\\frac{N}{\\left(1+i\\cdot \\frac{n}{12}\\right)}$$ bastará con susutituir y despejar el tipo de interés implícito,\n\n$$45000=\\frac{50000}{\\left(1+x\\cdot \\frac{12}{12}\\right)}$$ para obtener tipo de interés al que están cotizando los pagarés en este momento\n\n$$i=0.1111(11,11\\%)$$\n:::\n\n5.  ¿Cuál es el precio de una Letra del Tesoro comprada en el mercado secundario con un tipo de interés implícito del 2,066% y faltando 225 días para su vencimiento?\n\n<!-- -->\n\na.  98,725%.\n\nb.  98,505%.\n\nc.  98,630%.\n\nd.  98,850%.\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nEmpleamos la fórmula del precio de una letra, en capitalización simple y base 360:\n\n$$P_0=\\frac{100}{\\left(1+i\\cdot \\frac{d}{360}\\right)}$$\n\ndonde al sustituir y calcular\n\n$$P_0=\\frac{100}{\\left(1+\\:0.02066\\cdot \\frac{225}{360}\\right)}$$ tenemos un resultado de\n\n$$P_0=98.725\\% $$\n:::\n\n6.  ¿Cuál es el precio entero (precio efectivo) de un bono del Estado el día 18/12/2021, sabiendo que su cotización (precio ex cupón) es 101,275%, que paga cupones constantes anuales del 3,20% y que su vencimiento es el 31/1/2025?\n\n\n```{=html}\n<!-- -->\n```\n\na.  101,661%\n\nb.  98,461%\n\nc.  101,275%\n\nd.  104,089%\n\n::: {.callout-note appearance=\"simple\"}\nPara resolver esta pregunta hemos de calcular el cupón corrido y sumarlo a su precio de cotización (o precio ex cupón) que es conocido e igual a 101,275%. Por tanto, planteamos la fórmula del cupón corrido,\n\n$$CC=\\frac{D_c}{D_t}\\cdot C$$\n\ndonde,\n\n-   $CC$, es el cupón corrido.\n\n-   $D_{c}$, es el tiempo transcurrido desde el pago del último cupón.\n\n-   $D_{t}$, es el tiempo que transcurre entre el pago de dos cupones consecutivos\n\n-   $C$, es el importe del cupón que se paga periódicamente.\n\nAhora debemos realizar el cálculo para conocer el tiempo (en días) que ha transcurrido desde el pago del último cupón hasta la fecha presente (18/12/2021), y para ello sabemos que la próxima fecha del cupón que se paga periódicamente es el 31/1/2022 (ya que el vencimiento es el 31/1/2025).\n\nPor tanto calculamos su diferencia, sabiendo que desde el 18/12/2021 al 31/1/2022 van 43 días más el día corriente. Es decir 44 días, luego habrán transcurrido un total de 321 días (365-44) desde que se cobrara el último cupón.\n\nLo que implica que el cupón devengado y no cobrado es un rendimiento implícito que acumula este bono a la fecha de su valoración.\n\nAhora sustituimos en la fórmula y calculamos,\n\n$$CC=\\frac{321}{365}\\cdot 0.032=0.02814(2.82\\%)$$ Luego, el precio efectivo será la suma del precio ex cupón más el cupón corrido,\n\n$$P_{efectivo}=101.275\\%+2.814\\%=104.089\\%$$\n:::\n\n------------------------------------------------------------------------\n\n## Fiscalidad\n\nEn el caso de personas físicas, los **rendimientos de los activos de renta fija (implícitos o explícitos) se tratan como rendimientos de capital mobiliario y se integran en la base imponible del ahorro en el IRPF**. Los intereses (cupones) se gravan por el importe íntegro cobrado, mientras que el reembolso o transmisión (rendimientos implícitos) se gravan por la diferencia entre el valor de transmisión y el de adquisición, teniendo en cuenta los gastos inherentes de adquisición y transmisión.\n\nLa tributación se realiza mediante una tarifa progresiva del 19% al 26%, y la **retención aplicable es del 19%, excepto en el caso de Letras del Tesoro**, cuyo rendimiento no está sujeto a retención, y los rendimientos derivados de la venta de valores de renta fija antes de su vencimiento, donde el importe de los cupones pagados sí está sujeto a retención.\n\n## Ejercicios tipo test\n\n1.  Si la duración de una cartera de renta fija es de 6,5 y el horizonte temporal del inversor es de 5 años, podemos afirmar que:\n\n<!-- -->\n\na.  Nada de ello puede inferirse\n\nb.  El inversor está asumiendo un menor riesgo de precio con relación a una cartera perfectamente inmunizada.\n\nc.  La cartera esta perfectamente inmunizada.\n\nd.  Para inmunizar es necesario reducir la duración de la cartera.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nLa **inmunización** busca **igualar la duración de la cartera con el horizonte temporal** del inversor para conseguir que el valor final de la inversión sea el previsto al inicio.\n\n::: {.cell type='rmdtip'}\n\\BeginKnitrBlock{rmdtip}<div class=\"rmdtip\">\n\nCuando llevamos a cabo una inversión en activos de renta fija o monetarios, pueden ocurrir los siguientes casos:\n\n+  Si $D > H$, esto es, **si la duración es mayor que el horizonte temporal de la inversión a cartera NO estará inmunizada** y en la medida que el horizonte temporal es inferior a la duración se incurre en una situación de **riesgo de precio**.\n\n+ Si $D = H$, entonces la **duración de la cartera es igual al horizonte temporal de la inversión** y en consecuencia **la cartera estará inmunizada**.\n\n+ Si $D < H$, esto es, **si la duración es menor que el horizonte temporal de la inversión la cartera NO estará inmunizada** y en la medida en que la duración de la inversión es menor que el horizonte temporal, se incurre en una situación de **riesgo de reinversión**.\n\n</div>\\EndKnitrBlock{rmdtip}\n:::\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n2.  Dado un bono cupón cero que cotiza a la par, con vencimiento a 2 años y rentabilidad del 3%, ¿cuál será su duración?\n\n<!-- -->\n\na.  2\n\nb.  1\n\nc.  1.5\n\nd.  No se dan datos suficientes para contestar la pregunta.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nDe la expresión general para el cálculo de la duración, se puede deducir que un **bono cupón cero** (un solo flujo en la fecha de vencimiento) tiene una **duración igual a su vencimiento**.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n3.  El bono A tiene una duración de 5 y el bono B de 8.75. Los dos cotizan a una TIR del 1.75%. Si se produce una subida de la TIR (homogénea para todos los tramos de la curva) del 0.25%.\n\n<!-- -->\n\na.  El precio del bono A bajará un 1.23%\n\nb.  El precio del bono B bajará un 2.15%\n\nc.  El precio del bono A se verá menos afectado que el del bono B.\n\nd.  Todas las respuestas son correctas.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nCalculamos la variación relativa del precio del bono A y del B, para ello empleamos la siguiente fórmula:\n\n$$\\frac{\\Delta P}{P}\\simeq  \\frac{P_1-P_0}{P_0}\\simeq \\left(-D_{corregida}\\right)\\cdot\\Delta TIR$$ donde la Duración Corregida ($D_C$), se obtiene tras dividir la Duración entre uno más la TIR:\n\n$$D_{corregida}=\\frac{D}{\\left(1+TIR\\right)}$$ Así, podemos calcular para el bono A:\n\n$$\\frac{\\Delta P}{P}\\simeq-\\left[\\frac{5}{\\:\\left(1+0.0175\\right)}\\right]\\cdot 0.25\\simeq-1.22850\\simeq-1.23\\%$$ Y, para el bono B tenemos que:\n\n$$\\frac{\\Delta P}{P}\\simeq-\\left[\\frac{8.75}{\\:\\left(1+0.0175\\right)}\\right]\\cdot 0.25\\simeq-2.14987\\simeq\n-2.15\\%$$\n\nPor el segundo **principio de Malkiel** una variación dada en la TIR de un bono, cuanto mayor sea el plazo hasta su vencimiento, mayor será su variación en el precio.\n\nDe forma que, si se produce una subida de la TIR (homogénea para todos los tramos de la curva) del 0.25%, podemos afirmar que las tres repuestas (a, b y c) son correctas.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n4.  Respecto a la duración y el concepto de inmunización, determine cuál de las siguientes afirmaciones es correcta:\n\n<!-- -->\n\na.  Dado un bono cuya duración es menor que el horizonte temporal, el incremento en su TIR supondrá una bajada en el rendimiento total de la inversión.\n\nb.  Dado un bono cuya duración es mayor que el horizonte temporal, el incremento en su TIR supondrá una bajada en el rendimiento total de la inversión.\n\nc.  Si la duración y el horizonte temporal del bono coinciden, no se puede predecir el impacto de un movimiento en la TIR.\n\nd.  En una cartera inmunizada, la rentabilidad no depende de variaciones en la duración de los bonos que la componen.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la b**.\n\nCuando la **duración es menor que el horizonte temporal** de la cartera (D \\> HT), diremos que el **riesgo de reinversión** domina sobre el riesgo de precio, con lo que la rentabilidad efectiva de la cartera aumentará a medida que se incrementan los tipos de interés, y viceversa. (a es incorrecta)\n\nCuando la **duración es mayor que el horizonte temporal** de la cartera (D \\> HT), el **riesgo de precio** domina al riesgo de reinversión, con lo que la **rentabilidad** efectiva de la cartera **disminuirá** a medida que **aumenten los tipos** de interés, y viceversa. (b es correcta)\n\n**Cualquier alteración de los tipos de interés modifica la duración de la cartera**. De esta forma, aunque la duración y el horizonte temporal del bono coincidan (inmunizado), **SÍ se puede predecir el impacto de un movimiento en la TIR calculando la duración corregida** del bono en cuestión.\n\nLa **inmunización** es una técnica que exigirá **reequilibrar permanentemente la cartera** para mantener la igualdad entre horizonte temporal y duración, **a causa de las variaciones de la duración de los bonos que la componen**, pero también a causa de posibles **cambios en el horizonte temporal**, lo que, en realidad, limita su aplicación.(d es incorrecta)\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n5.  Suponga un bono con TIR del 4%, plazo de cinco años y cupones anuales del 3.5% pagaderos el 31 de diciembre de cada ejercicio. Determine cuál de las siguientes afirmaciones es falsa:\n\n<!-- -->\n\na.  Un aumento de la TIR supondrá una disminución de la duración.\n\nb.  Si, en lugar de pagar los cupones anualmente, lo hiciera semestralmente, su duración sería menor.\n\nc.  El día 1 de enero la duración será mayor que el día 30 de diciembre del ejercicio anterior.\n\nd.  El día 1 de enero el bono tendrá una duración menor que el día 30 de junio del mismo ejercicio.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nCuando **aumenta la TIR, disminuye la duración** (a, es verdadera).\n\nA **mayor frecuencia en el pago de cupones menor duración** (b, es verdadera).\n\nA mayor plazo de amortización, mayor duración. **El corte del cupón (pago del cupón) provoca un aumento de la duración del bono**. Se da la paradoja que justamente **el día 1 de enero**, a pesar de haber transcurrido tan solo un día respecto al 31 de diciembre (pago/cobro del cupón), y que por tanto, el pazo a vencimiento será menor, **la duración aumenta en lugar de reducirse**. Esto se debe a la **proximidad o lejanía al pago del cupón** que al estar muy próximo el pago del cupón y, por tanto, haber mayor cupón corrido, la duración es menor. Por el contrario, si está lejano el pago del próximo cupón, el cupón corrido es reducido y la duración es mayor (c es verdadera).\n\nLa respuesta d, a priori debería ser verdadera ya que a menor plazo de amortización, menor duración (ya que desde el mes de enero hasta el mes de junio del mismo ejercicio, lógicamente se reduce el plazo de amortización en 5 meses). Dicho de otro modo, **el día 1 de enero la duración debería de ser \"mayor\" que el día 30 de junio del mismo ejercicio**.\n\nSin embargo esto, **no siempre es así**. Para **bonos que cotizan bajo la par con vencimientos largos, el incremento de la duración a medida que aumenta el plazo de amortización, presenta un punto de inflexión a partir del cual se invierte la tendencia inicial**.\n\nVeamos, en el caso de nuestro bono, si cotiza bajo par:\n\n$$TIR > Cupón => Precio < 100\\%$$ Luego por propiedades, **sabemos que como cotiza bajo par y el vencimiento no es corto (5 años)**, de forma que la **respuesta d es falsa**. Si bien para determinarlo con **mayor precisión debemos antes calcular su duración para ambos momentos del tiempo**.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n6.  Determine cuál de las siguientes afirmaciones respecto a la sensibilidad de un bono NO es correcta:\n\n<!-- -->\n\na.  La sensibilidad nos permite aproximar cuál será el impacto en el precio del bono de variaciones en la TIR.\n\nb.  La sensibilidad nos permite establecer con exactitud cuál será el nuevo precio de un bono, si la TIR cambia.\n\nc.  Desde un punto de vista del precio, si esperamos bajadas en los tipos de interés, buscaremos bonos con sensibilidad alta.\n\nd.  La duración de un bono es una medida de sensibilidad de éste.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la b**.\n\nLa **sensibilidad** de un bono es una medida que relaciona las **variaciones absolutas del precio** de un bono con las **variaciones absolutas de su TIR**. Por lo tanto, la sensibilidad nos proporciona información en términos absolutos acerca de cual será la variación del precio de un bono.\n\nLa **sensibilidad** nos permite **aproximar** cuál será el impacto en **el precio** del bono ante **variaciones en la TIR**.\n\nAnte la misma variación de tipos de interés del mercado, la mayoría de los productos de renta fija que **vencen más tarde son más sensibles en precio**. Por el contrario, los bonos y productos de renta fija que **vencen más pronto** tienen normalmente una **menor sensibilidad** en precio.\n\nLa **duración** es la media de los periodos de pago de los flujos de un bono ponderados por el peso que representa el valor actual de los mismos en el precio del bono. La duración **puede definirse también como una medida de la sensibilidad relativa de un bono**. Es decir, relaciona las variaciones relativas del precio con las variaciones relativas de la TIR.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n7.  ¿Qué variación porcentual estima que tendrá el precio de un bono, suponiendo las siguientes características y que la TIR experimenta una subida de 100 p.b.?\n\n| **Datos:**            |\n|:----------------------|\n| Precio entero: 104,00 |\n| Duración: 14,3        |\n| TIR actual: 5,25%     |\n\na)  14,30%\n\nb)  13,59%\n\nc)  -13,59%\n\nd)  -14,30%\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nEn primer lugar vamos a recordar la fórmula de la duración de Macaulay (o simplemente la \"duración\"):\n\n$$D=1\\cdot\\frac{F_1\\cdot\\left(1+TIR\\right)^{-1}}{P}+2\\cdot\\frac{F_2\\cdot\\left(1+TIR\\right)^{-2}}{P}+.....+n\\cdot\\frac{F_n\\cdot\\left(1+TIR\\right)^n}{P}$$\n\nQue, en este caso, es un dato que nos dan en el enunciado del ejercicio:\n\n$$D=Duración\\ de\\ Macaulay=14.3$$\n\nEn segundo lugar, vamos a calcular la duración corregida $D.C.$ (también conocida como duración modificada o de Hicks), a partir de la duración de Macaulay $D$.\n\n$$D.C.=\\frac{D}{(1+TIR)}=\\frac{14.3}{(1+0.0525)}=13.59\\%$$\n\nY, en tercer y último lugar, calculamos la variación en el precio ante un aumento de la TIR de 100 p.b.(recordad, cada punto porcentual contiene 100 puntos básicos):\n\n$$\\frac{\\Delta\\ P}{P}=-D_{corregida}\\cdot\\Delta TIR=(-13.59\\%)\\cdot 1\\%=-13.59\\% $$\n\nNotesé que también cabe la posibilidad de realizar los calculos anteriores en tantos por uno, en lugar de hacerlo en tantos por cien. De forma análoga, serían:\n\n$$D.C.=\\frac{D}{(1+TIR)}\\cdot \\frac{1}{100}=\\frac{14.3}{(1+0.0525)}=0.1359$$ $$\\frac{\\Delta\\ P}{P}=-D_{corregida}\\cdot\\Delta TIR=(-0.1359)\\cdot 1=-0.1359$$\n\nEn definitiva, este bono se estima que experimentará una caída del precio entero en torno al 13,59%.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n8.  Hemos comprado un bono al 98,735%. Al cabo de un tiempola TIR del bono pasa del 5,23% al 5%. Siendo laa duración inicial de de 3 años y su duración en el momento actual de 2,36 años. ¿Cuál será el nuevo precio estimado del bono?:\n\n<!-- -->\n\na.  99,582%.\n\nb.  99,244%.\n\nc.  98,806%.\n\nd.  99.442%.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la b**.\n\nEn primer lugar, calcularemos la Duración corregida utilizando la siguiente fórmula:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}$$\n\ndonde,\n\n$$D_{corregida}=\\frac{2.36}{(1+0.0523)}=2.2427$$\n\nAhora aplicamos la siguiente fórmula, la cuál nos permite estimar el efecto en el precio de un bono ante variaciones en la TIR una vez conocida la duración corregida, el precio inicial y la variación experimentada en la TIR:\n\n$$P_1\\simeq P_0\\cdot\\left[1+((-D_{corregida})\\cdot\\Delta TIR)\\right]$$\n\ndonde, al sustituir y calcular tenemos un resultado de:\n\n$$P_1\\simeq 0.98735\\cdot\\left[1+((-2.2427)\\cdot (-0.0023))\\right]=0.99244(99.244\\%)$$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n9.  Para un mismo bono, su tasa de rentabilidad efectiva a vencimiento es mayor cuando:\n\n<!-- -->\n\na.  El tipo de interés de reinversión es igual a su TIR de adquisición.\n\nb.  Ninguna de las anteriores.\n\nc.  El tipo de interés de reinversión es superior a su TIR de adquisición\n\nd.  El tipo de interés de reinversión es inferior a su TIR de adquisición.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nLa TIR es una buena medida de la rentabilidad a vencimiento de un bono si se reinvierten los cupones a una tasa igual a la propia TIR. Si la reinversión se hace a tipos superiores, la rentabilidad efectiva a vencimiento será superior a la TIR de adquisición.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n10. ¿Cuál ha sido la rentabilidad efectiva de la siguiente operación si suponemos que el inversor reinvierte los cupones anuales, según las condiciones siguientes?:\n\n| **Datos:**                         |\n|:-----------------------------------|\n| Compra de bono en fecha: 15-5-2010 |\n| Vencimiento: 15-5-2014             |\n| Cupón anual: 3,75%                 |\n| Valor nominal: 1.000 euros         |\n| TIR de adquisición: 4,380%         |\n| Precio de compra del bono: 97,733% |\n\n| Tipos de interés a 1 año: |\n|:--------------------------|\n| 15-5-2011: 4,55%          |\n| 15-5-2012: 4,67%          |\n| 15-5-2013: 4,75%          |\n\na)  4,399%.\n\nb)  4,425%.\n\nc)  4,380%.\n\nd)  3,750%.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nRecordemos que la Tasa de Rentabilidad Efectiva (TRE) se define como aquella rentabilidad media anual que tiene en cuenta las tasas de reinversión de los ingresos de una operación, medida mediante capitalización compuesta.Y su expresión es la siguiente:\n\n$$V_f=V_0\\left(1+i_{TRE}\\right)^n$$\n\nPara calcular el valor final, primero tenemos que calcular los ingresos que fueron reinvertidos cada uno de los años 2011, 2012, 2013:\n\n$$F_1=C_1\\cdot\\left(1+i_1\\right)\\cdot\\left(1+i_2\\right)\\cdot\\left(1+i_3\\right)=37.5\\cdot1.0455\\cdot1.0467\\cdot1.0475=42.9896$$\n\n$$F_2=C_2\\cdot\\left(1+i_2\\right)\\cdot\\left(1+i_3\\right)=37.5\\cdot1.0467\\cdot1.0475=41.115$$\n\n$$F_3=C_3\\cdot\\left(1+i_3\\right)=37.5\\cdot1.0475=39.2812$$\n\nCalculamos también el flujo a vencimiento de 2014, esto es, el cupón percibido (que no se reinvierte) más el reembolso del nominal:\n\n$$F_4=N_4+C_4=1000+37.5=1037.5$$\n\nUna vez calculados todos los flujos generados durante el periodo de madurez del bono, los sumamos para conocer el valor final de la inversión:\n\n$$V_f=F_1+F_2+F_3+F_4=42.9896+41.115+39.2812+1037.5=1160.8826$$ Una vez que conocemos el valor final $V_f$ y el valor inicial $V_0$, planteamos la fórmula de la TRE y resolvemos por el tipo de interés $i_{TRE}$:\n\n$$V_f=V_0\\left(1+i_{TRE}\\right)^n$$ Donde,\n\n$$i_{TRE}=\\left(\\frac{V_f }{V_0 }\\right)^{\\frac{1 }{n }}-1$$ Que al sustituir y calcular, obtenemos un resultado de:\n\n$$i_{TRE}=\\left(\\frac{ 1160.8826}{977.33 }\\right)^{\\frac{1 }{4 }}-1=0.04399(4.399\\%)$$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n11. ¿Qué son los S.T.R.I.P.S. de deuda pública?\n\n<!-- -->\n\na.  Son bonos con cupones emitidos por el Tesoro Público.\n\nb.  Son bonos cupón cero emitidos por el Tesoro Público.\n\nc.  Son operaciones de agregación y desagregación sobre bonos y obligaciones del Estado (cupones y principal) que lleva a cabo el propio Tesoro Público.\n\nd.  Son operaciones de agregación y desagregación sobre bonos y obligaciones del Estado (cupones y principal) que llevan a cabo los \"markets makers\".\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nLos bonos y Obligaciones del Estado denominados \"segregables\" o \"S.T.R.I.P.S., presentan las siguientes características:\n\n-   Posibilidad de \"segregación\": esto es, posibilidad de separar cada bono en \"n\" valores (los llamados S.T.R.I.P.S. ), uno por cada pago que la posesión del bono dé derecho a recibir. Así, de un bono a 5 años podrían obtenerse 6 \"strips\": uno por cada pago de cupón anual, y un sexto por el principal , al cabo de los 5 años. Cada uno de estos strips puede ser posteriormente negociado de forma diferenciada del resto de strips procedentes del bono.\n\n-   Esta operación de segregación transforma un activo de rendimiento explícito (bono u obligación) en una serie de valores de rendimiento implícito - bonos cupón cero -, cuya fecha de vencimiento y valor de reembolso coinciden con los de los cupones y principal del activo originario. Los bonos cupón cero tienen unas características financieras peculiares que los hacen especialmente atractivos para determinados inversores. Los strips son una forma de cubrir esa demanda sin necesidad de aumentar la gama de valores emitidos por el Tesoro.\n\n-   Además, se permite realizar la operación inversa a la descrita, es decir, la reconstitución del activo originario a partir de los bonos cupón cero procedentes de su segregación.\n\nEn España, el Tesoro comenzó a emitir valores segregables en julio de 1997. La segregación propiamente dicha y la negociación de los \"S.T.R.I.P.S.\" resultantes se inició en enero de 1998.\n\nLas entidades que poseen la autorización y potestad para llevar a cabo la segregación y reconstitución de bonos, son los llamados Creadores de Mercado o \"markets makers\". Los creadores de mercado, son un conjunto de entidades y agentes financieros, que ayudan y facilitan a que haya mucha más liquidez en el mercado tanto primario como secundario de deuda pública.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n12. En el momento de emisión de un bono del Estado en el mercado primario (donde lo adquirimos directamente de su emisor, el Tesoro). Puede, o no, existir una diferencia entre el valor nominal y del precio de suscripción:\n\n<!-- -->\n\na.  Si el valor nominal y el precio de suscripción coinciden: decimos que se trata de una emisión a la par.\n\nb.  El valor nominal está por encima del precio de suscripción: decimos que se trata de una emisión bajo la par o con descuento. Esto implica que hay una rentabilidad positiva implícita que se pondrá de manifiesto a vencimiento.\n\nc.  El valor nominal se sitúa por debajo del precio de suscripción: decimos que se trata de una emisión sobre la par o con prima. Esto implica que hay una rentabilidad negativa implícita a vencimiento que también debe ser considerada.\n\nd.  Todas las anteriores.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nEn el momento de emisión de un bono del Estado en el mercado primario, pueden darse tres circunstancias:\n\n-   El valor nominal y el precio de suscripción coinciden: es una emisión a la par.\n\n-   El valor nominal está por encima del precio de suscripción: emisión bajo la par o con descuento. Esto implica que hay una rentabilidad implícita que se pondrá de manifiesto a vencimiento.\n\n-   El valor nominal se sitúa por debajo del precio de suscripción: emisión sobre la par o con prima. Al revés que en el caso anterior, aquí existe una rentabilidad negativa implícita a vencimiento que también debe ser considerada.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n13. Los rendimientos de los bonos y obligaciones del Estado español se consideran en el ámbito del IRPF:\n\n<!-- -->\n\na.  Si proceden de la venta del activo financiero sería ganancia o pérdida patrimonial sin estar sujeto a retención alguna.\n\nb.  Si proceden de la percepción de intereses por el cobro de cupones sería rendimiento del capital mobiliario sin estar sujeto a retención alguna.\n\nc.  Si proceden de la percepción de intereses por el cobro de cupones sería rendimiento del capital mobiliario estando sujeto a retención.\n\nd.  Si proceden de la venta del activo financiero sería rendimiento del capital mobiliario sujeto a retención.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nTributación de los Bonos y Obligaciones del Estado\n\nCUPÓN\n\n1.  Calificación\n\nEl importe de los intereses percibidos -cupón- tiene la consideración de rendimiento de capital mobiliario del ejercicio en que se perciben.\n\n2.  Tributación\n\nLos intereses -cupón- generados por los Bonos y Obligaciones del Estado tributan al tipo del 19% hasta los 6.000 €, el tramo de la base liquidable entre 6.000 € y los 44.000 € tributa al 21% y el tramo que excede de 50.000 € tributa al 23% en el ejercicio 2016.\n\n3.  Retención\n\nSobre este rendimiento se aplica **retención a cuenta del IRPF (19%)**.\n\nTRANSMISIÓN O AMORTIZACIÓN\n\n1.  Calificación\n\nLos rendimientos generados en la transmisión o amortización de los Bonos u Obligaciones del Estado tienen la consideración de **rendimiento de capital mobiliario, sujeto al IRPF**.\n\n2.  Tributación\n\nDicho rendimiento se computará como la diferencia entre el valor de transmisión o amortización y el precio de adquisición o suscripción de los Bonos u Obligaciones que se transmiten o amortizan.\n\nNo obstante, el rendimiento así calculado podrá reducirse en los gastos accesorios de adquisición y enajenación que se justifiquen adecuadamente.\n\nEl rendimiento neto tributará al 19% hasta los 6.000 €, el tramo de la base liquidable entre 6.000 € y 44.000 € tributa al 21% y el tramo que excede de 50.000 € tributa al 23% en los ejercicios 2016\n\n3.  Retención\n\n**Los rendimientos derivados de la transmisión o amortización de Bonos y Obligaciones del Estado no están sometidos a retención a cuenta del IRPF**, salvo el los casos de contratos de cuentas basadas en operaciones sobre dichos valores (\"cuentas financieras\") o cuando opere la norma \"anti-lavado\" de cupón.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n14. Si tengo un bono cupón cero que actualmente está cotizando al 95,425% y su valor nominal es del 100% y además le quedan 437 días para vencimiento y la base es Act/365. ¿Cuál es su rentabilidad efectiva anual?:\n\n<!-- -->\n\na.  3,99%\n\nb.  3,87%\n\nc.  4,02%\n\nd.  Ninguna de las anteriores\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nAplicamos el precio de una letra para plazo superior al año (capitalización compuesta):\n\n$$P_0=\\frac{100}{(1+i)^{d/365}}$$\n\ndonde,\n\n-   $P_0$, es el precio de la letra, expresado en porcentaje sobre el nominal.\n\n-   $i$, es el tipo de interés en tantos por uno.\n\n-   $d$, es el número de días que ha mantenido el inversor la letra en su poder.\n\nAl desejar el tipo de interés, tenemos:\n\n$$i=\\left(\\frac{100}{P_0}\\right)^{\\left(\\frac{365}{d}\\right) }-1$$\n\nSustituimos y calculamos,\n\n$$i=\\left(\\frac{100}{95.425}\\right)^{\\left(\\frac{365}{437}\\right) }-1=0.0398(3.99\\%)$$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n15. Dentro de la clasificación de los spread de curvas de tipos de interés, ¿Cuál de las siguientes afirmaciones es correcta?:\n\n<!-- -->\n\na.  El spread entre plazos nos indica la diferencia en la calidad crediticia.\n\nb.  El spread entre curvas nos indica las expectativas de mercado en cuanto a la evolución del tipo de interés.\n\nc.  El spread entre plazos nos indica la calidad crediticia de cada emisor en cada plazo\n\nd.  Ninguna de las anteriores\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nEl spread de curvas de tipos de interés se clasifican en:\n\n-   Spread entre plazos, que indica las expectativas de mercado en cuanto a la evolución del tipo de interés.\n\n-   Spread entre curvas, que indica la diferencia en la calidad crediticia de cada emisor para cada plazo.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n16. Cuál/es de las siguiente/s teoría/s explica/n la estructura temporal de los tipos de interés (ETTI):\n\n<!-- -->\n\na.  La Teoría de las Expectativas del Mercado.\n\nb.  La Teoría de la Preferencia por la Liquidez.\n\nc.  La Teoría del Hábitat Preferido.\n\nd.  Todas las anteriores.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la d**.\n\nLas teorías explicativas de la estructura temporal de los tipos de interés (ETTI) son:\n\n-   De la Teoría de la Preferencia por la liquidez, se infiere que la curva de rendimientos de una inversión será siempre creciente en función del tiempo, ya que en principio un inversor preferirá invertir a corto plazo que a largo plazo, al poder conseguir convertir antes en liquidez los activos si así le fuera necesario.\n\n-   La Teoría de las Expectativas del Mercado, enuncia que la ETTI se forma de manera exclusiva en función de las expectativas que tienen los potenciales inversores en relación a cómo van a evolucionar los tipos de interés en el futuro. Por tanto, la curva sería creciente cuando se espere que los tipos vayan a subir debido a que haya por ejemplo una elevada inflación, y sería descendente cuando la expectativa fuera de bajada de la inflación.\n\n-   La Teoría del Hábitat Preferido, por su parte ha tratado de sintetizar estas teorías, estableciendo que el equilibrio de mercado obliga a que la oferta y la demanda de activos financieros debe ajustar sus plazos en cada momento, según el \"hábitat\" en el que nos encontremos, existiendo primas para aquellos vencimientos donde hay una demanda insuficiente, de tal manera que dichas primas serían las que inducirían a los inversores al abandono de sus hábitats preferidos, pasando de largo a corto plazo o viceversa.\n\nNota: encontramos también en algunos textos la llamada Teoría de la Segmentación de Mercados, según la cual los mercados de renta fija están segmentados por productos, cuyos precios se establecen mediante las leyes de la oferta y la demanda de cada mercado. En base a esto, la forma de la curva podrá variar según los mercados (corto plazo, medio plazo o largo plazo), y tener cualquier forma. Si se demanda más a corto que a largo, la curva estaría invertida; si fuera al revés sería ascendente.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n17. Ante una percepción de mayor riesgo por parte del mercado respecto a una emisión de renta fija privada:\n\n<!-- -->\n\na.  Se ampliará el diferencial de rentabilidad (spread) con el que cotiza respecto a la deuda pública.\n\nb.  Se reducirá el diferencial de rentabilidad (spread) con el que cotiza respecto a la deuda pública.\n\nc.  Se mantendrá el diferencial de rentabilidad (spread) con el que cotiza respecto a la deuda pública.\n\nd.  Ninguna de las anteriores es correcta.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nSe ampliará el diferencial de rentabilidad con el que cotiza respecto a la deuda pública como consecuencia de una ampliación de la prima de riesgo descontada por el mercado.\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n18. ¿La duración corregida de un bono la definimos cómo?\n\n<!-- -->\n\na.  La duración dividida entre la TIR del bono.\n\nb.  La duración multiplicada por (1 + TIR) del bono.\n\nc.  La duración dividida entre (1 + TIR) del bono.\n\nd.  La duración del bono multiplicada por un punto básico.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la c**.\n\nPor definición la duración corregida es, como podemos ver en su fórmula, la duración (de Macaulay) dividida entre 1 + la TIR del bono:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}=\\frac{D}{\\left(1+TIR\\right)} $$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n19. ¿Cómo expresamos matemáticamente la sensibilidad absoluta de un bono?:\n\n<!-- -->\n\na.  Como la duración corregida multiplicada por el precio entero del bono.\n\nb.  Como la duración multiplicada por el precio entero del bono.\n\nc.  Como la duración modificada dividida por 1 más la TIR y multiplicada por el precio entero del bono.\n\nd.  Ninguna de las anteriores.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nLa Sensibilidad absoluta refleja variaciones absolutas del precio de un activo de renta fija, ante variaciones absolutas de la TIR; siendo su expresión matemática la siguiente:\n\n$$S={Duracion\\,corregida }\\cdot{Precio\\,entero}$$ Notesé que esta expresión se utiliza el caso de haber tomado como la duración corregida la siguiente fórmula:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}\\cdot\\frac{1}{100}$$\n\nEn el caso de haber tomado como la duración corregida de la siguiente fórmula:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}=\\frac{D}{\\left(1+TIR\\right)} $$\n\nEntonces la sensibilidad, necesariamente, debería expresarse así:\n\n$$S= Duracion\\,corregida \\cdot \\frac{Precio\\,entero}{100}$$ Y NO así:\n\n$$S={Duracion\\,corregida }\\cdot{Precio\\,entero}$$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n20. Compramos un bono al 102,505%. Pasado algún tiempo la TIR del bono pasa del 5% al 6%. Siendo la duración actual del bono de 4,5 años. ¿Cuál será el nuevo precio estimado del bono?:\n\n<!-- -->\n\na.  98,112%.\n\nb.  97,624%.\n\nc.  95,322%.\n\nd.  Ninguna de las anteriores.\n\n<details>\n\n<summary>\n\n</summary>\n\n::: {.callout-note appearance=\"simple\"}\nLa respuesta **correcta es la a**.\n\nEn primer lugar, calcularemos la Duración corregida utilizando la siguiente fórmula:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}$$ donde,\n\n$$D_{corregida}=\\frac{4.5}{(1+0.05)}=4.2857$$\n\nAhora aplicamos la siguiente fórmula, la cuál nos permite estimar el efecto en el precio de un bono ante variaciones en la TIR una vez conocida la duración corregida, el precio inicial y la variación experimentada en la TIR:\n\n$$P_1\\simeq P_0\\cdot\\left[1+((-D_{corregida})\\cdot\\Delta TIR)\\right]$$\n\ndonde, al sustituir y calcular tenemos un resultado de:\n\n$$P_1\\simeq 1.02505\\cdot\\left[1+((-4.2857)\\cdot 0.01)\\right]=0.981119(98.112\\%)$$\n:::\n\n</details>\n\n------------------------------------------------------------------------\n\n## Ejercicios prácticos\n\n### Renta Fija I (2021)\n\nDisponemos de la siguiente información relativa a un bono de la empresa DELTA\n\n-   NOMINAL 100.000 EUR\n-   CUPON ANUAL 4,50\n-   TIR A VENCIMIENTO 5%\n-   FECHA VALOR 1-08-2021\n-   FECHA VENCMIENTO 31-12-2024\n\n1.  Hallar el precio del bono a 1-08-2021\n\n<!-- -->\n\na.  101063,9461\n\nb.  100660,8685\n\nc.  102432,2342\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nEn primer lugar tenemos que calcular el precio entero de este bono. Para ello utilizaremos la siguiente metodología de cálculo:\n\n$$P_0=\\sum_{ t=1}^{ n}\\frac{F_t}{(1+r)^{t}}$$\n\ndonde,\n\n-   $P_0$, es el precio entero de un bono o valor actual del mismo ($V_0$).\n\n-   $F_t$, Flujos a percibir por la tenencia de un bono (cupón y principal).\n\n-   $r$, es la TIR.\n\n-   $t$, es el tiempo.\n\nDonde si sustituimos por los datos del problema y calculamos, tenemos que el precio actual (a fecha 1-08-2021) del bono es de:\n\n$$P_{(1-08-21)}=\\frac{4500}{\\left(1+0.05\\right)^{\\frac{152}{365}}}+\\frac{4500}{\\left(1+0.05\\right)^{1+\\frac{152}{365}}}+\\frac{4500}{\\left(1+0.05\\right)^{2+\\frac{152}{365}}}+\\frac{104500}{\\left(1+0.05\\right)^{3+\\frac{152}{365}}}$$ $$P_{(1-08-21)}=101063.94618$$\n:::\n\n------------------------------------------------------------------------\n\n2.  Calcular la duración del bono\n\n<!-- -->\n\na.  3,16286\n\nb.  3,85122\n\nc.  4,02241\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nEn este caso para calcular la Duración de Macaulay (o simplemente, la \"Duración\"), vamos a realizar el siguiente cálculo:\n\n$$D=\\frac{\\sum_{t=1}^{n}\\frac{F_t\\cdot t}{\\left(1+r\\right)^t}}{P}$$\n\ndonde,\n\n-   $D$, Duración de Macaulay.\n\n-   $F_t$, Flujos a percibir por la tenencia de un bono (cupón y principal).\n\n-   $P$, es el precio entero de un bono o valor actual del mismo ($V_0$).\n\n-   $r$, es la TIR.\n\n-   $t$, es el tiempo.\n\nDe manera que si sustituimos por los datos del problema y calculamos, tenemos que la Duración del bono es de:\n\n$$D=\\frac{\\left(\\frac{152}{365}\\right)\\frac{4500}{\\left(1+0.05\\right)^{\\frac{152}{365}}}+\\left(1+\\frac{152}{365}\\right)\\frac{4500}{\\left(1+0.05\\right)^{1+\\frac{152}{365}}}+\\left(2+\\frac{152}{365}\\right)\\frac{4500}{\\left(1+0.05\\right)^{2+\\frac{152}{365}}}+\\left(3+\\frac{152}{365}\\right)\\frac{104500}{\\left(1+0.05\\right)^{3+\\frac{152}{365}}}}{101063.94618}$$\n\n$$D=3.162$$\n:::\n\n------------------------------------------------------------------------\n\n3.  Si la TIR sube 40 p.b. calcular el nuevo precio del bono\n\n<!-- -->\n\na.  99142,747\n\nb.  101025,372\n\nc.  99846.562\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la c**.\n\nEn primer lugar calculamos la duración corregida a partir de la duración que hemos calculado en el apartado anterior:\n\n$$D_{corregida}=\\frac{Duracion\\,de\\, Macaulay}{\\left(1+TIR\\right)}=\\frac{D}{\\left(1+TIR\\right)} $$ De forma que nuestra duración corregida será:\n\n$$D_{corregida}=\\frac{3.162}{1+0.05}=3.01142$$ Para estimar la variación del precio ante variaciones en la TIR emplearemos la siguiente expresión,\n\n$$P_1\\simeq P_0\\cdot\\left[1+((-D_{corregida})\\cdot\\Delta TIR)\\right]$$\n\ndonde,\n\n-   $P_1$, es el precio estimado del bono ante una variación de la TIR.\n\n-   $P_0$, es el precio actual del bono .\n\n-   $D_{corregida}$, es la duración corregida.\n\nSi sustituimos por los datos del problema y calculamos, tenemos que el nuevo precio del bono ante una subida de la TIR sube de 40 p.b. será de:\n\n$$P_1\\simeq 101063.94618\\left(1+\\left(\\left(-3.01142\\right)\\cdot \\:0.004\\right)\\right)=99846.56222$$\n:::\n\n------------------------------------------------------------------------\n\n### Renta Fija II (2021)\n\n1.  La empresa ALFA quiere comprar un paquete de bonos de la empresa DELTA. La información de la que disponemos es la siguiente:\n\n-   Nominal: 100.000 eur\n\n-   Cupón anual: 9%\n\n-   TIR a vencimiento: 5.75%\n\n-   Fecha valor: 2-10-2021\n\n-   Fecha vencimiento: 31-12-2024\n\nPara la compra de este paquete de bonos la de 500.000 euros. La entidad le ofrece dos empresa ALFA acude a su entidad bancaria y solicita una financiación propuestas:\n\n1.  Préstamo de 500.000 euros a 30 meses, periodicidad de cuotas mensuales, tipo de interés nominal 4,15%, comisiones 0.\n\n2.  Préstamo de 500.000 euros a 36 meses, periodicidad de cuotas mensuales, tipo de interés nominal 4%, comisión de apertura 0,25%.\n\n3.  Hallar el precio del bono a 2-10-2021:\n\n<!-- -->\n\na.  116.115,8357\n\nb.  117.054,9150\n\nc.  115.633,1742\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nPara realizar los cálculos a mano debemos de usar la siguiente fórmula que describe un descuento de flujos:\n\n$$P_0=\\sum_{ t=1}^{ n}\\frac{F_t}{(1+r)^{t}}$$\n\ndonde,\n\n-   $P_0$, es el precio entero de un bono o valor actual del mismo ($V_0$).\n\n-   $F_t$, Flujos a percibir por la tenencia de un bono (cupón y principal).\n\n-   $r$, es la TIR.\n\n-   $t$, es el tiempo.\n\nSi sustituimos los valores y calculamos\n\n$$P_0=\\frac{9}{\\left(1+0.0575\\right)^{\\frac{90}{365}}}+\\frac{9}{\\left(1+0.0575\\right)^{1+\\frac{90}{365}}}+\\frac{9}{\\left(1+0.0575\\right)^{2+\\frac{90}{365}}}+\\frac{109}{\\left(1+0.0575\\right)^{3+\\frac{90}{365}}}$$ el precio del bono en el momento actual, tenemos que:\n\n$$P_0=116.11583$$\n\nObtenemos el mismo resultado con la calculadora Casio FC 200v:\n\nFunción: BOND\n\nSet: Annu/Date\n\nd1= 02102021 + EXE\n\nd2= 31122024 + EXE\n\nRDV= 100 + EXE\n\nCPN= 9 + EXE\n\nPRC= 0 + EXE\n\nYLD= 5.75 + EXE\n\nPRC= SOLVE #vuelves sobre \"PRC\" y pulsas \"SOLVE\" para obtener los siguientes resultados:\n\nPRC= -109.335 #es el precio ex cupón\n\nINT= -6.7808 #es el cupón corrido\n\n**CST= -116.1158 #es el precio + cupón corrido**\n\nNota: siempre devuelve en negativo por que entiende que es un desembolso (compra).\n:::\n\n------------------------------------------------------------------------\n\n2.  Calcular la duración del bono:\n\n<!-- -->\n\na.  2,745312480\n\nb.  2,90232678\n\nc.  2,804290364\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la c**.\n\nPara calcular la Duración de Macaulay (o simplemente Duración)\n\n$$D=\\frac{\\sum_{t=1}^{n}\\frac{F_t\\cdot t}{\\left(1+r\\right)^t}}{P}$$\n\ndonde,\n\n-   $D$, Duración de Macaulay.\n\n-   $F_t$, Flujos a percibir por la tenencia de un bono (cupón y principal).\n\n-   $P$, es el precio entero de un bono o valor actual del mismo ($V_0$).\n\n-   $r$, es la TIR.\n\n-   $t$, es el tiempo.\n\nDe forma que si sustituimos y calculamos,\n\n$$D=\\frac{\\left(\\frac{90}{365}\\right)\\frac{9}{\\left(1+0.0575\\right)^{\\frac{90}{365}}}+\\left(1+\\frac{90}{365}\\right)\\frac{9}{\\left(1+0.0575\\right)^{1+\\frac{90}{365}}}+\\left(2+\\frac{90}{365}\\right)\\frac{9}{\\left(1+0.0575\\right)^{2+\\frac{90}{365}}}+\\left(3+\\frac{90}{365}\\right)\\frac{109}{\\left(1+0.0575\\right)^{3+\\frac{90}{365}}}}{116.11583}$$\n\ntenemos q ue la Duracuón es de:\n\n$$D=2.80429$$\n:::\n\n------------------------------------------------------------------------\n\n3.  ¿En función de la TAE. ¿cuál es la propuesta de financiación más favorable para la empresa ALFA?\n\n    1.  Préstamo de comisiones 0. 500.000 euros a 30 meses, periodicidad de cuotas mensuales, tipo de interés nominal 4,15%,\n\n    2.  Préstamo de 500.000 euros a 36 meses, periodicidad de cuotas mensuales, tipo de interés nominal 4 %, comisión de apertura 0,25%.\n\n<!-- -->\n\na.  1\n\nb.  2\n\nc.  Son idénticas\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nEn primer lugar vamos a calcular cuál sería la talla S con comisiones cero, ya que en este caso sabemos que la tasa actual equivalente coincidirá con la tira anual. Es decir que nos están pidiendo calcular cuál será el tipo de interés anual efectivo en capitalización compuesta.\n\nSi lo calculamos empleando la fórmula:\n\n$$TAE=\\left(1+\\frac{j\\left(m\\right)}{m}\\right)^m-1$$ simplemente, susutituimos y calculamos:\n\n$$TAE=\\left(1+\\frac{0.0415}{12}\\right)^{12}-1=0.04229\\left(\\approx 4.23\\%\\right)$$\n\nPodemos usar la calculadora financiera Casio FC200V y FC100V,\n\n-   Función: \"CNVR\"\n\n-   n = 12\n\n-   I% = 4.15\n\n-   EFF = variable a resolver (pulsamos sobre la tecla \"SOLVE\")\n\nY, nos devueve un resultado de:\n\n$$EFF = 4.2299\\% = TAE$$\n\nPara calcular la TAE con comisiones usaremos la calculadora financiera con la función CMPD. De esta forma nos permitirá llevar a cabo el **primer paso hallar la cuota**:\n\nCALCULADORA FC-100V/200V\n\nModo: CMPD\n\nSet: Begin/End (Pagos al inicio o al final del periodo)\n\nn: 36 (Número de periodos)\n\nI%: 4 (Tipo de interés nominal)\n\n**PV: 500000 (Valor presente o principal sin aplicar la comisión)**\n\nPMT: 0 (Importe de los pagos periódicos, **es lo que buscamos¿¿??**)\n\nFV: 0 (Valor futuro)\n\nP/Y: 12 (Número de pagos anuales)\n\nC/Y: 12 (Número de periodos dentro de un año)\n\nCálculo: Podemos calcular n, I, PV, PMT o FV con el SOLVE, dando los otros datos De forma que si **resolvemos por PMT tenemos que el resultado es de: 14761.9925 €**\n\nConocida la cuota, **el segundo paso será hallar el tipo de interés efectivo anual, pagadero mensual**:\n\nModo: CMPD\n\nSet: Begin/End (Pagos al inicio o al final del periodo)\n\nn: 36 (Número de periodos)\n\n**I%: 0 (Tipo de interés efectivo)**\n\n**PV: 500000(1-0.0025) (Valor presente o principal tras aplicar la comisión de apertura)**\n\n**PMT: 14761.9925 (dejamos el PMT que hemos calculado)**\n\nFV: 0 (Valor futuro)\n\nP/Y: 12 (Número de pagos anuales)\n\n**C/Y: 1 (Número de compuestos dentro de un año, introducimos el valor 1 ya que buscamos el efectivo anual o TAE)**\n\nCálculo: Podemos calcular n, I, PV, PMT o FV con el SOLVE, dando los otros datos De forma que si **resolvemos por I% y tenemos que el resultado es de: 4.2467%**\n\nDe la misma forma, **podemos plantear una ecuación donde conocemos el valor actual y el importe a pagar durante las próximas 36 mensualidades**. Es decir, que si **despejamos cuál es el tipo de interés que equivale** a esta operación; en donde lo que que tenemos a la parte izquierda de la **igualdad es lo efectivamente recibido desde la entidad** financiera (500000-0.0025 x 5000000), y al lado derecho, **lo que efectivamente acabaremos pagando**: la renta constante de 36 términos (de 14761.992 euros) que deberemos de amortizar:\n\n$$\\left(500000\\left(1-0.0025\\right)\\right)=14761.9925\\left(\\frac{1-\\left(1+\\frac{i_{12}}{12}\\right)^{-36}}{\\frac{i_{12}}{12}}\\right)$$\n\ndonde el tipo efectivo mensual es igual a 0.003472\n\n$$TAE=(1+0.003472)^{12}-1=0.0424(4.247\\%)$$\n:::\n\n------------------------------------------------------------------------\n\n### Crédito y TAE\n\nEl cliente se plantea realizar otra inversión en carteras por valor de 150.000 y pretende solicitar financiación por el citado importe a su entidad financiera ALFA. Esta le ofrece las siguientes condiciones:\n\n-   Importe 150.000 euros\n\n-   Plazo 36 meses. Amortización por el sistema de mensualidad constante o sistema francés\n\n-   Tipo interés 3,75%\n\n-   Comisión apertura 0,25%\n\nSe pide:\n\n1.  ¿A cuánto ascienden los costes de la operación que pagará el cliente si solicita el crédito?\n\n<!-- -->\n\na.  9.204,68\n\nb.  17.250\n\nc.  12.380,42\n\nd.  8.425,40\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\n**Respuesta correcta la a.**\n\n| Cuadro resumen |              |\n|----------------|--------------|\n| Cuota          | 4.411,94 €   |\n| TAE            | 3,99 %       |\n| TIN anual      | 3,82 %       |\n| Coste Total    | 9.204,68 €   |\n| Comisiones     | 375,00 €     |\n| Intereses      | 8.829,68 €   |\n| Capital        | 150.000,00 € |\n\nCalculamos la cuota,\n\n$$150000=c\\cdot\\frac{1-\\left(1+\\frac{0.0375}{12}\\right)^{-36}}{\\frac{0.0375}{12}}$$\n\n$$c=4411.93545\\dots $$ Calculamos la TAE,\n\n$$(150000(1-0.0025))=4411.93545\\cdot\\frac{1-\\left(1+\\frac{TAE}{12}\\right)^{-36}}{\\frac{TAE}{12}}$$\n\n$$TAE=3.99\\% $$\n\nCalculamos la comisión de apertura,\n\n$$C=150000\\cdot \\:0.0025=375$$ El pago total de cuotas,\n\n$$T_C= 36\\cdot \\:4411.93545=158829.6762$$\n\nSumamos ahora, la comisión de apertura y el pago total de cuotas, y\n\n$$C_T=75+158829.6762=159204.6762$$\n\npor diferencia, obtenemos \"A cuánto ascienden los costes de la operación que pagará el cliente si solicita el crédito\":\n\n$$159204.6762-150000=9204.6762$$\n\nSiendo el **cuadro de amortización** de la operación el siguiente:\n\n| Periodo | Cuota    | Capital  | Intereses | Pendiente  |\n|---------|----------|----------|-----------|------------|\n| 1       | 4.411,94 | 3.943,19 | 468,75    | 146.056,81 |\n| 2       | 4.411,94 | 3.955,51 | 456,43    | 142.101,31 |\n| 3       | 4.411,94 | 3.967,87 | 444,07    | 138.133,44 |\n| 4       | 4.411,94 | 3.980,27 | 431,67    | 134.153,17 |\n| 5       | 4.411,94 | 3.992,71 | 419,23    | 130.160,46 |\n| 6       | 4.411,94 | 4.005,18 | 406,75    | 126.155,28 |\n| 7       | 4.411,94 | 4.017,70 | 394,24    | 122.137,58 |\n| 8       | 4.411,94 | 4.030,26 | 381,68    | 118.107,32 |\n| 9       | 4.411,94 | 4.042,85 | 369,09    | 114.064,47 |\n| 10      | 4.411,94 | 4.055,48 | 356,45    | 110.008,99 |\n| 11      | 4.411,94 | 4.068,16 | 343,78    | 105.940,83 |\n| 12      | 4.411,94 | 4.080,87 | 331,07    | 101.859,96 |\n| 13      | 4.411,94 | 4.093,62 | 318,31    | 97.766,34  |\n| 14      | 4.411,94 | 4.106,42 | 305,52    | 93.659,92  |\n| 15      | 4.411,94 | 4.119,25 | 292,69    | 89.540,67  |\n| 16      | 4.411,94 | 4.132,12 | 279,81    | 85.408,55  |\n| 17      | 4.411,94 | 4.145,03 | 266,90    | 81.263,52  |\n| 18      | 4.411,94 | 4.157,99 | 253,95    | 77.105,53  |\n| 19      | 4.411,94 | 4.170,98 | 240,95    | 72.934,55  |\n| 20      | 4.411,94 | 4.184,01 | 227,92    | 68.750,54  |\n| 21      | 4.411,94 | 4.197,09 | 214,85    | 64.553,45  |\n| 22      | 4.411,94 | 4.210,21 | 201,73    | 60.343,24  |\n| 23      | 4.411,94 | 4.223,36 | 188,57    | 56.119,88  |\n| 24      | 4.411,94 | 4.236,56 | 175,37    | 51.883,32  |\n| 25      | 4.411,94 | 4.249,80 | 162,14    | 47.633,52  |\n| 26      | 4.411,94 | 4.263,08 | 148,85    | 43.370,44  |\n| 27      | 4.411,94 | 4.276,40 | 135,53    | 39.094,03  |\n| 28      | 4.411,94 | 4.289,77 | 122,17    | 34.804,27  |\n| 29      | 4.411,94 | 4.303,17 | 108,76    | 30.501,09  |\n| 30      | 4.411,94 | 4.316,62 | 95,32     | 26.184,48  |\n| 31      | 4.411,94 | 4.330,11 | 81,83     | 21.854,37  |\n| 32      | 4.411,94 | 4.343,64 | 68,29     | 17.510,73  |\n| 33      | 4.411,94 | 4.357,21 | 54,72     | 13.153,51  |\n| 34      | 4.411,94 | 4.370,83 | 41,10     | 8.782,68   |\n| 35      | 4.411,94 | 4.384,49 | 27,45     | 4.398,19   |\n| 36      | 4.411,94 | 4.398,19 | 13,74     | 0,00       |\n:::\n\n------------------------------------------------------------------------\n\n2.  Otra entidad financiera, BETA, le ofrece financiar la operación con las siguientes condiciones:\n\n-   Importe 150.000 euros\n\n-   Plazo 36 meses con el mismo sistema de amortización que el préstamo anterior\n\n-   Tipo interés 3,90%\n\n-   Comisión apertura 0\n\nEn función de la TAE, ¿cuál es la opción más favorable para el cliente?\n\na.  Opción ALFA\n\nb.  Opción BETA\n\nc.  Son iguales\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la b.**\n\nSi calculamos la cuota:\n\n$$\n150000=c\\frac{1-\\left(1+\\frac{0.039}{12}\\right)^{-36}}{\\frac{0.039}{12}} \n$$\n\n$$\nc=4421.92817\\dots\n$$\n\nCalculamos la TAE:\n\n$$\n150000=4421.92817\\cdot \\frac{1-\\left(1+\\frac{TAE}{12}\\right)^{-36}}{\\frac{TAE}{12}}\n$$\n\n$$\nTAE=3.97 \\%\n$$\n\n|                 |                |                |\n|-----------------|----------------|----------------|\n|                 | Opción ALFA    | Opción BETA    |\n| Cuota           | 4.411,94 €     | 4.421,93 €     |\n| **TAE**         | **3,99 %**     | **3,97 %**     |\n| TIN anual       | 3,82 %         | 3,97 %         |\n| **Coste Total** | **9.204,68 €** | **9.189,41 €** |\n| Comisiones      | 375,00 €       | 0,00 €         |\n| Intereses       | 8.829,68 €     | 9.189,41 €     |\n| Capital         | 150.000,00 €   | 150.000,00 €   |\n\n+----------------------------+---+\n| ### Cuadro de Amortización |   |\n+----------------------------+---+\n\n| Periodo | Cuota    | Capital  | Intereses | Pendiente  |\n|---------|----------|----------|-----------|------------|\n| 1       | 4.421,93 | 3.934,43 | 487,50    | 146.065,57 |\n| 2       | 4.421,93 | 3.947,22 | 474,71    | 142.118,36 |\n| 3       | 4.421,93 | 3.960,04 | 461,88    | 138.158,31 |\n| 4       | 4.421,93 | 3.972,91 | 449,01    | 134.185,40 |\n| 5       | 4.421,93 | 3.985,83 | 436,10    | 130.199,57 |\n| 6       | 4.421,93 | 3.998,78 | 423,15    | 126.200,79 |\n| 7       | 4.421,93 | 4.011,78 | 410,15    | 122.189,02 |\n| 8       | 4.421,93 | 4.024,81 | 397,11    | 118.164,20 |\n| 9       | 4.421,93 | 4.037,89 | 384,03    | 114.126,31 |\n| 10      | 4.421,93 | 4.051,02 | 370,91    | 110.075,29 |\n| 11      | 4.421,93 | 4.064,18 | 357,74    | 106.011,11 |\n| 12      | 4.421,93 | 4.077,39 | 344,54    | 101.933,72 |\n| 13      | 4.421,93 | 4.090,64 | 331,28    | 97.843,07  |\n| 14      | 4.421,93 | 4.103,94 | 317,99    | 93.739,14  |\n| 15      | 4.421,93 | 4.117,28 | 304,65    | 89.621,86  |\n| 16      | 4.421,93 | 4.130,66 | 291,27    | 85.491,20  |\n| 17      | 4.421,93 | 4.144,08 | 277,85    | 81.347,12  |\n| 18      | 4.421,93 | 4.157,55 | 264,38    | 77.189,57  |\n| 19      | 4.421,93 | 4.171,06 | 250,87    | 73.018,51  |\n| 20      | 4.421,93 | 4.184,62 | 237,31    | 68.833,89  |\n| 21      | 4.421,93 | 4.198,22 | 223,71    | 64.635,67  |\n| 22      | 4.421,93 | 4.211,86 | 210,07    | 60.423,81  |\n| 23      | 4.421,93 | 4.225,55 | 196,38    | 56.198,26  |\n| 24      | 4.421,93 | 4.239,28 | 182,64    | 51.958,98  |\n| 25      | 4.421,93 | 4.253,06 | 168,87    | 47.705,91  |\n| 26      | 4.421,93 | 4.266,88 | 155,04    | 43.439,03  |\n| 27      | 4.421,93 | 4.280,75 | 141,18    | 39.158,28  |\n| 28      | 4.421,93 | 4.294,66 | 127,26    | 34.863,61  |\n| 29      | 4.421,93 | 4.308,62 | 113,31    | 30.554,99  |\n| 30      | 4.421,93 | 4.322,62 | 99,30     | 26.232,37  |\n| 31      | 4.421,93 | 4.336,67 | 85,26     | 21.895,70  |\n| 32      | 4.421,93 | 4.350,77 | 71,16     | 17.544,93  |\n| 33      | 4.421,93 | 4.364,91 | 57,02     | 13.180,02  |\n| 34      | 4.421,93 | 4.379,09 | 42,84     | 8.800,93   |\n| 35      | 4.421,93 | 4.393,33 | 28,60     | 4.407,60   |\n| 36      | 4.421,93 | 4.407,60 | 14,32     | 0,00       |\n:::\n\n------------------------------------------------------------------------\n\n### Renta Fija (valoración y fiscalidad IRPF)\n\nLa empresa Palmira SA realizar una emisión de bonos que cotizará en el Mercado AIAF de Renta Fija. El vencimiento programado es a 2,5 años y ofrece un cupón cuya rentabilidad es del 5,75%. El pago del cupón es semestral. El nominal de cada título es de 600€.\n\nSe pide:\n\n<!-- -->\n\n1.  Si pasados 6 meses la rentabilidad anual de mercado es del 7,00% y la semestral es del 3,441% ¿Cuál será su precio de mercado?\n\n<!-- -->\n\na.  587,51€\n\nb.  516,17€\n\nc.  650,96€\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nPasados 6 meses el **precio de mercado** de este bono, expresado como un **porcentaje** sobre el valor nominal, es de:\n\n$$P_0=\\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^1}+\\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^2}+\\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^3}+\\frac{\\frac{5.75}{2}+100}{\\left(1+0.03441\\right)^4}$$\n\n$$P_0=97.91812\\% $$\n\nSi el precio obtenido del bono **ahora lo expresamos en euros**, tenemos que:\n\n$$P_0=\\frac{97.91812}{100}\\cdot \\:\\:600=587.50872\\ euros$$\n:::\n\n------------------------------------------------------------------------\n\n2.  ¿Cuál será su duración y su duración modificada?\n\n<!-- -->\n\na.  1,917 y 1,791\n\nb.  1,850 y 1,729\n\nc.  1,871 y 1,748\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nDonde su duración será de:\n\n$$D=\\frac{0.5\\cdot \\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^1}+1\\cdot \\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^2}+1.5\\cdot \\frac{\\frac{5.75}{2}}{\\left(1+0.03441\\right)^3}+2\\cdot \\frac{\\frac{5.75}{2}+100}{\\left(1+0.03441\\right)^4}}{97.91812}=1.91671$$\n\n$$D=1.91671$$\n\ny, la duración modificada de\n\n$$D_m=\\frac{1.91671}{\\left(1+0.07\\right)}=1,791317757$$\n:::\n\n------------------------------------------------------------------------\n\n3.  Calcule el coste fiscal derivado de las siguientes operaciones realizadas en el mismo período impositivo por un contribuyente del Impuesto sobre la Renta de las Personas Físicas que fuese titular de 50 bonos adquiridos a un precio unitario de 650€:\n\n<!-- -->\n\n-   Cobro del primer cupón semestral.\n\n-   Transmisión de 50 bonos,una vez percibido el primer cupón semestral, a un precio unitario de 625€, y pagando una comisión de venta del 0,10% sobre el efectivo de venta.\n\na.  -243,43€\n\nb.  23,15625€\n\nc.  142,5€\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa respuesta **correcta es la a**.\n\nPor el importe de los intereses percibidos, es decir, el cobro del primer cupón semestral (nominal= 600 euros y cupón del 5,75%), se aplicará una **retención a cuenta del IRPF del 19%**, esto es:\n\n$$50\\left(600\\cdot \\:0.0575\\right)\\left(0.19\\right)=327.75$$\n\nLuego, como se cobrará el **importe NETO de impuestos**, no supone un coste fiscal de carácter explícito, sino implícito; y que no tendremos que considerar en la resolución del ejercicio planteado:\n\n$$50\\left(600\\cdot \\:0.0575\\right)\\left(1-0.19\\right)=1397.25$$\n\nSin embargo, el rendimiento obtenido por la transmisión del título (diferencia entre el valor de transmisión y el de adquisición, minorado por los gastos de compra y venta justificados) no está sujeto a retención. De forma que, supondrá un coste fiscal para un contribuyente en el Impuesto sobre la Renta de las Personas Físicas, teniendo la consideración de un rendimiento de capital mobiliario, sujeto y que tributará al 19%.\n\n$$\\left(50\\left(625-650\\right)-\\left(0.001\\cdot \\:50\\cdot \\:625\\right)\\right)\\cdot \\:0.19=-243.4375$$ Como los rendimientos obtenidos por el contribuyente son negativos, se podrán compensarán con el saldo positivo de otros rendimientos del capital mobiliario obtenidos en este mismo período impositivo, teniendo como límite ese saldo positivo. Y, si este fuera insuficiente, su importe se podrá compensará con el saldo positivo de las ganancias y pérdidas patrimoniales que se declaren en el otro componente de la base imponible del ahorro, con el límite del 25 por ciento de dicho saldo positivo.\n:::\n\n------------------------------------------------------------------------\n\n### Renta Fija (Duración modificada y nuevo precio ante variación de la TIR)\n\nSe dispone de la siguiente información relativa a un bono de la empresa ABC:\n\nFecha Valor: 15/10/2022\n\nFecha de Vencimiento: 15/10/2027\n\nCupón anual: 4,25%\n\nTIR: 3,27%\n\nNominal: 1.000 euros\n\nSe pide:\n\n1.  Calcular la duración modificada del bono\n\n\n```{=html}\n<!-- -->\n```\n\na.  4,47\n\nb.  4,62\n\nc.  4,22\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nCalculamos el precio entero:\n\n$$P_0=\\frac{4.25}{\\left(1+0.0327\\right)^{1\\:}}+\\frac{4.25}{\\left(1+0.0327\\right)^{2\\:}}+\\frac{4.25}{\\left(1+0.0327\\right)^{3\\:}}+\\frac{4.25}{\\left(1+0.0327\\right)^{4\\:}}+\\frac{104.25}{\\left(1+0.0327\\right)^{5\\:}}$$\n\n$$P_0=104.45372$$\n\nCalculamos la Duración:\n\n$$D=\\frac{1\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{1\\:}}+2\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{2\\:}}+3\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{3\\:}}+4\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{4\\:}}+5\\cdot \\frac{104.25}{\\left(1+0.0327\\right)^{5\\:}}}{104.45372}$$ $$D=4.61828$$\n\nCalculamos la Duración corregida:\n\n$$D_c=\\frac{\\frac{1\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{1\\:}}+2\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{2\\:}}+3\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{3\\:}}+4\\cdot \\frac{4.25}{\\left(1+0.0327\\right)^{4\\:}}+5\\cdot \\frac{104.25}{\\left(1+0.0327\\right)^{5\\:}}}{104.45372}}{\\left(1+0.0327\\right)}$$\n\n$$D_c=4.47204$$\n:::\n\n------------------------------------------------------------------------\n\n2.  Calcular el precio si la TIR de mercado disminuye en 75 puntos básicos utilizando la duración modificada.\n\n\n```{=html}\n<!-- -->\n```\n\na.  1.079,57\n\nb.  1.009,50\n\nc.  1.044,54\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nAplicamos la siguiente fórmula donde se indica, cual será aproximadamente el nuevo precio tras la variación de la TIR:\n\n$$P_1\\simeq P_0\\cdot\\left[1+((-D_{corregida})\\cdot\\Delta TIR)\\right]$$ Calculamos, $$P_1\\simeq \\left(104.45372\\cdot 10\\right)\\cdot \\left[1+\\left(\\left(-4.47\\right)\\cdot -0.0075\\right)\\right]=1079.55530$$ Y obtenemos como resultado:\n\n$$P_1\\simeq 1079.55530$$\n:::\n\n------------------------------------------------------------------------\n\n### Renta préstamo francés\n\n29. ¿Cuál es la cuota mensual de un préstamo de 135.000 euros a 60 meses, tipo de interés 8,20% anual, método de amortización sistema francés?\n\n\n```{=html}\n<!-- -->\n```\n\na.  11.168,71€\n\nb.  2.750,25€\n\nc.  11.070,00€\n\nd.  922,50€\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa fórmula general para calcular el **valor actual de una renta constante** es:\n\n$$V_0=c\\cdot\\frac{1-\\left(1+i\\right)^{-n}}{i}$$ Sustituimos los datos del problema y calculamos:\n\n$$135000=c\\cdot \\frac{1-\\left(1+\\frac{0.0820}{12}\\right)^{-60}}{\\frac{0.0820}{12}}$$ Obtenemos como resultado la cuota mensual en euros:\n\n$$c=2750.25326$$\n:::\n\n------------------------------------------------------------------------\n\n### Renta perpetua\n\n33. Calcular la tasa de descuento que debería haber en el mercado para que las acciones de una empresa que ha prometido un dividendo constante durante toda su vida de 0,25€, estén cotizando a 3,10€ en el momento actual.\n\n\n```{=html}\n<!-- -->\n```\n\na.  Menor que 8%.\n\nb.  8%\n\nc.  Entre 8% y 9%.\n\nd.  Mayor que 9%.\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa tasa de descuento requerida (o tasa de rendimiento requerida) para que las acciones de esta empresa coticen a 3,10€ con un dividendo constante de 0,25€ es aproximadamente 8,06%.\n\nPara calcular la tasa de descuento requerida para que las acciones de una empresa que paga un dividendo constante cotizen a un precio específico, puedes utilizar el modelo de valoración de acciones llamado el Modelo de Gordon-Shapiro o el Modelo de Gordon. La fórmula básica para calcular la tasa de descuento (tasa de rendimiento requerida) es la siguiente:\n\n$$P_0 = \\frac{D} {K_e - g}$$\n\nDonde:\n\n-   $P_0$ es el precio actual de la acción (3,10€ en este caso).\n\n-   $D$ es el dividendo constante que la empresa paga (0,25€ en este caso).\n\n-   $K_e$ es la tasa de descuento o tasa de rendimiento requerida.\n\n-   $g$ es la tasa de crecimiento de los dividendos (como se indica en el enunciado, en este caso, se asume constante, por lo que $g$ es igual a cero).\n\nAhora, podemos resolver para $K_e$:\n\n$$3.1=\\:\\frac{0.25}{K_e} \\:;\\:K_e=0.080645161290323$$\n\nLa tasa de descuento requerida (o tasa de rendimiento requerida) para que las acciones de esta empresa coticen a 3,10€ con un dividendo constante de 0,25€ es aproximadamente 8,06%.\n:::\n\n------------------------------------------------------------------------\n\n12. La cartera de inversión de un cliente ha obtenido una rentabilidad acumulada a tres años del 18,90% y su benchmark, del 13%. Además, sabemos que, para el mismo período de tiempo, la beta de la cartera fue del 1,20, y el tracking error del 7%. Calcular la ratio de información, si el tipo de interés del activo sin riesgo fue del 1,25%.\n\n\n```{=html}\n<!-- -->\n```\n\na.  0,8429\n\nb.  0,0492\n\nc.  3,8750\n\nd.  0,6643\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\n$$RI=\\frac{E_p-E_m}{TE}$$ $$RI=\\frac{18.9-13}{7}=0.84285$$\n:::\n\n------------------------------------------------------------------------\n\n13. El tipo de interés del dólar de Estados Unidos a 6 meses es del 2,75%, y el del euro para el mismo período es del 1,80%. El tipo de cambio al contado es EUR/USD 1,0566. Calcular el seguro de cambio a un año entre estas dos divisas:\n\n\n```{=html}\n<!-- -->\n```\n\na.  EUR/USD 1,0665\n\nb.  EUR/USD 1,0616\n\nc.  EUR/USD 1,0856\n\nd.  EUR/USD 1,0756\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nLa fórmula que aplicamos es la del seguro de cambio\n\n$$F_{EUR/USD}=S_{EUR/USD}\\cdot \\frac{1+i_{USD}\\cdot \\frac{6}{12}}{1+i_{EUR\\:\\:}\\cdot \\frac{6}{12}}$$\n\nAplicamos con los datos del enunciado, y calculamos\n\n$$F_{EUR/USD}=1.0566\\cdot \\frac{1+0.0275\\cdot \\frac{6}{12}}{1+0.0180\\:\\:\\cdot \\frac{6}{12}}$$ obteniendo como resultado $$EUR/USD = 1.06157...$$\n:::\n\n------------------------------------------------------------------------\n\n18. Un inversor adquiere una acción cuya desviación estándar es 9% y una covarianza con el mercado de 0,02. La rentabilidad esperada del activo sin riesgo es del 1,25%. Asumiendo que las expectativas de rentabilidad del mercado son del 12% y su desviación estándar de 8%. Según el Capital Asset Pricing Model (CAPM), ¿cuál será la rentabilidad esperada de la acción?\n\n\n```{=html}\n<!-- -->\n```\n\na.  34,84%\n\nb.  3,48%\n\nc.  3,94%\n\nd.  27,79%\n\n::: {.callout-tip collapse=\"true\"}\n### Solución\n\nUtilizaremos la SML, ya que es la ecuación que no sirve para calcular la rentabilidad esperada de una acción:\n\n$$E_i=R_f+\\left(E_m−R_f\\right)⋅β_{i,m}$$\n\nCalculamos, primero, la beta entre la acción y el mercado:\n\n$$\\beta _{i,\\:m}=\\frac{\\sigma _{i,\\:m}}{\\sigma _m^2}=\\frac{0.02}{0.08^{2\\:}}=3.125$$\n\nY, la SML\n\n$$E_i=0.0125+\\left(0.12−0.0125\\right)\\cdot 3.125$$\n\nnos da como resultado:\n\n$$E_i=0.3484375=34.84\\%$$\n:::\n\n------------------------------------------------------------------------\n\n(modelo de Gordon)\n\nEl modelo de crecimiento constante del dividendo, también conocido como modelo de Gordon, establece que el valor de una acción se determina por la fórmula cuando el dividendo tiene una tasa de crecimiento constante:\n\n$$V_0 = \\frac{D_1}{K_e- g}$$\n\nEsta fórmula se utiliza para calcular el valor presente de una renta periódica perpetua de una cuantía D (1), creciente geométricamente a una tasa g, y descontada a un tipo K.\n\nEn este caso, V (0) es el valor estimado de una compañía, D(1) es el dividendo esperado del año siguiente, K es el coste de los recursos propios de la compañía considerada y g es su tasa perpetua de crecimiento de los dividendos.\n",
    "supporting": [
      "2023-CLASES-MARTA_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}